//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Slin.Facturacion.Proxies.ServicioMantenimiento
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name = "ListaSexo", Namespace = "http://schemas.datacontract.org/2004/07/Slin.Facturacion.BusinessEntities", ItemName = "Sexo")]
    public class ListaSexo : System.Collections.Generic.List<Slin.Facturacion.Proxies.ServicioMantenimiento.Sexo>
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Sexo", Namespace = "http://www.slin.com.pe")]
    public partial class Sexo : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string CodigoField;

        private string DescripcionField;

        private int IdSexoField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdSexo
        {
            get
            {
                return this.IdSexoField;
            }
            set
            {
                this.IdSexoField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name = "ListaEstado", Namespace = "http://schemas.datacontract.org/2004/07/Slin.Facturacion.BusinessEntities", ItemName = "Estado")]
    public class ListaEstado : System.Collections.Generic.List<Slin.Facturacion.Proxies.ServicioMantenimiento.Estado>
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Estado", Namespace = "http://schemas.datacontract.org/2004/07/Slin.Facturacion.BusinessEntities")]
    public partial class Estado : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string DescripcionField;

        private int IdEstadoField;

        private int IdEstadoSUNATField;

        private string RutaImagenField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEstado
        {
            get
            {
                return this.IdEstadoField;
            }
            set
            {
                this.IdEstadoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEstadoSUNAT
        {
            get
            {
                return this.IdEstadoSUNATField;
            }
            set
            {
                this.IdEstadoSUNATField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RutaImagen
        {
            get
            {
                return this.RutaImagenField;
            }
            set
            {
                this.RutaImagenField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name = "ListaEmpresa", Namespace = "http://schemas.datacontract.org/2004/07/Slin.Facturacion.BusinessEntities", ItemName = "Empresa")]
    public class ListaEmpresa : System.Collections.Generic.List<Slin.Facturacion.Proxies.ServicioMantenimiento.Empresa>
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Empresa", Namespace = "http://schemas.datacontract.org/2004/07/Slin.Facturacion.BusinessEntities")]
    public partial class Empresa : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string CodEmpresaField;

        private string CodPaisField;

        private string CodigoUbigeoField;

        private string DepartamentoField;

        private string DireccionField;

        private string DistritoField;

        private string DomicilioFiscalField;

        private string DominioField;

        private string EmailField;

        private Slin.Facturacion.Proxies.ServicioMantenimiento.Estado EstadoField;

        private string FaxField;

        private System.DateTime FechaRegistroField;

        private string GroupField;

        private string IPField;

        private int IdEmpresaField;

        private int IdGrpField;

        private int NroField;

        private string PaginaWebField;

        private string PasswordField;

        private int PortField;

        private string ProvinciaField;

        private string RUCField;

        private string RazonComercialField;

        private string RazonSocialField;

        private string TelefonoField;

        private Slin.Facturacion.Proxies.ServicioMantenimiento.TipoDocumentoIdentidad TipoDocumentiIdentidadField;

        private string TipoLoginField;

        private Slin.Facturacion.Proxies.ServicioMantenimiento.Ubigeo UbigeoField;

        private string UrbanizacionField;

        private string Url_CompanyConsultField;

        private string Url_CompanyLogoField;

        private int UseSSLField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodEmpresa
        {
            get
            {
                return this.CodEmpresaField;
            }
            set
            {
                this.CodEmpresaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodPais
        {
            get
            {
                return this.CodPaisField;
            }
            set
            {
                this.CodPaisField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoUbigeo
        {
            get
            {
                return this.CodigoUbigeoField;
            }
            set
            {
                this.CodigoUbigeoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Departamento
        {
            get
            {
                return this.DepartamentoField;
            }
            set
            {
                this.DepartamentoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion
        {
            get
            {
                return this.DireccionField;
            }
            set
            {
                this.DireccionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Distrito
        {
            get
            {
                return this.DistritoField;
            }
            set
            {
                this.DistritoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DomicilioFiscal
        {
            get
            {
                return this.DomicilioFiscalField;
            }
            set
            {
                this.DomicilioFiscalField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dominio
        {
            get
            {
                return this.DominioField;
            }
            set
            {
                this.DominioField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Slin.Facturacion.Proxies.ServicioMantenimiento.Estado Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fax
        {
            get
            {
                return this.FaxField;
            }
            set
            {
                this.FaxField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaRegistro
        {
            get
            {
                return this.FechaRegistroField;
            }
            set
            {
                this.FechaRegistroField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Group
        {
            get
            {
                return this.GroupField;
            }
            set
            {
                this.GroupField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IP
        {
            get
            {
                return this.IPField;
            }
            set
            {
                this.IPField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEmpresa
        {
            get
            {
                return this.IdEmpresaField;
            }
            set
            {
                this.IdEmpresaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdGrp
        {
            get
            {
                return this.IdGrpField;
            }
            set
            {
                this.IdGrpField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Nro
        {
            get
            {
                return this.NroField;
            }
            set
            {
                this.NroField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaginaWeb
        {
            get
            {
                return this.PaginaWebField;
            }
            set
            {
                this.PaginaWebField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Port
        {
            get
            {
                return this.PortField;
            }
            set
            {
                this.PortField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Provincia
        {
            get
            {
                return this.ProvinciaField;
            }
            set
            {
                this.ProvinciaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RUC
        {
            get
            {
                return this.RUCField;
            }
            set
            {
                this.RUCField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RazonComercial
        {
            get
            {
                return this.RazonComercialField;
            }
            set
            {
                this.RazonComercialField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RazonSocial
        {
            get
            {
                return this.RazonSocialField;
            }
            set
            {
                this.RazonSocialField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono
        {
            get
            {
                return this.TelefonoField;
            }
            set
            {
                this.TelefonoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Slin.Facturacion.Proxies.ServicioMantenimiento.TipoDocumentoIdentidad TipoDocumentiIdentidad
        {
            get
            {
                return this.TipoDocumentiIdentidadField;
            }
            set
            {
                this.TipoDocumentiIdentidadField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoLogin
        {
            get
            {
                return this.TipoLoginField;
            }
            set
            {
                this.TipoLoginField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Slin.Facturacion.Proxies.ServicioMantenimiento.Ubigeo Ubigeo
        {
            get
            {
                return this.UbigeoField;
            }
            set
            {
                this.UbigeoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Urbanizacion
        {
            get
            {
                return this.UrbanizacionField;
            }
            set
            {
                this.UrbanizacionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url_CompanyConsult
        {
            get
            {
                return this.Url_CompanyConsultField;
            }
            set
            {
                this.Url_CompanyConsultField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url_CompanyLogo
        {
            get
            {
                return this.Url_CompanyLogoField;
            }
            set
            {
                this.Url_CompanyLogoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UseSSL
        {
            get
            {
                return this.UseSSLField;
            }
            set
            {
                this.UseSSLField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "TipoDocumentoIdentidad", Namespace = "http://schemas.datacontract.org/2004/07/Slin.Facturacion.BusinessEntities")]
    public partial class TipoDocumentoIdentidad : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string CodigoField;

        private string DescripcionField;

        private int IdTipoDocumentoIdentidadField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTipoDocumentoIdentidad
        {
            get
            {
                return this.IdTipoDocumentoIdentidadField;
            }
            set
            {
                this.IdTipoDocumentoIdentidadField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Ubigeo", Namespace = "http://schemas.datacontract.org/2004/07/Slin.Facturacion.BusinessEntities")]
    public partial class Ubigeo : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string CodigoUbigeoField;

        private string DescripcionField;

        private Slin.Facturacion.Proxies.ServicioMantenimiento.Distrito DistritoField;

        private int IdUbigeoField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoUbigeo
        {
            get
            {
                return this.CodigoUbigeoField;
            }
            set
            {
                this.CodigoUbigeoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Slin.Facturacion.Proxies.ServicioMantenimiento.Distrito Distrito
        {
            get
            {
                return this.DistritoField;
            }
            set
            {
                this.DistritoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUbigeo
        {
            get
            {
                return this.IdUbigeoField;
            }
            set
            {
                this.IdUbigeoField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Distrito", Namespace = "http://schemas.datacontract.org/2004/07/Slin.Facturacion.BusinessEntities")]
    public partial class Distrito : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string CodigoField;

        private string CodigoUbigeoField;

        private string DescripcionField;

        private int IdDistritoField;

        private Slin.Facturacion.Proxies.ServicioMantenimiento.Provincia ProvinciaField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoUbigeo
        {
            get
            {
                return this.CodigoUbigeoField;
            }
            set
            {
                this.CodigoUbigeoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdDistrito
        {
            get
            {
                return this.IdDistritoField;
            }
            set
            {
                this.IdDistritoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Slin.Facturacion.Proxies.ServicioMantenimiento.Provincia Provincia
        {
            get
            {
                return this.ProvinciaField;
            }
            set
            {
                this.ProvinciaField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Provincia", Namespace = "http://schemas.datacontract.org/2004/07/Slin.Facturacion.BusinessEntities")]
    public partial class Provincia : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string CodigoField;

        private Slin.Facturacion.Proxies.ServicioMantenimiento.Departamento DepartamentoField;

        private string DescripcionField;

        private Slin.Facturacion.Proxies.ServicioMantenimiento.Distrito DistritoField;

        private int IdProvinciaField;

        private Slin.Facturacion.Proxies.ServicioMantenimiento.ListaDistrito ListaDistritoField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Slin.Facturacion.Proxies.ServicioMantenimiento.Departamento Departamento
        {
            get
            {
                return this.DepartamentoField;
            }
            set
            {
                this.DepartamentoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Slin.Facturacion.Proxies.ServicioMantenimiento.Distrito Distrito
        {
            get
            {
                return this.DistritoField;
            }
            set
            {
                this.DistritoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProvincia
        {
            get
            {
                return this.IdProvinciaField;
            }
            set
            {
                this.IdProvinciaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Slin.Facturacion.Proxies.ServicioMantenimiento.ListaDistrito ListaDistrito
        {
            get
            {
                return this.ListaDistritoField;
            }
            set
            {
                this.ListaDistritoField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Departamento", Namespace = "http://schemas.datacontract.org/2004/07/Slin.Facturacion.BusinessEntities")]
    public partial class Departamento : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string CodigoField;

        private string DescripcionField;

        private int IdDepartamentoField;

        private Slin.Facturacion.Proxies.ServicioMantenimiento.ListaProvincia ListaProvinciaField;

        private Slin.Facturacion.Proxies.ServicioMantenimiento.Pais PaisField;

        private Slin.Facturacion.Proxies.ServicioMantenimiento.Provincia ProvinciaField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdDepartamento
        {
            get
            {
                return this.IdDepartamentoField;
            }
            set
            {
                this.IdDepartamentoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Slin.Facturacion.Proxies.ServicioMantenimiento.ListaProvincia ListaProvincia
        {
            get
            {
                return this.ListaProvinciaField;
            }
            set
            {
                this.ListaProvinciaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Slin.Facturacion.Proxies.ServicioMantenimiento.Pais Pais
        {
            get
            {
                return this.PaisField;
            }
            set
            {
                this.PaisField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Slin.Facturacion.Proxies.ServicioMantenimiento.Provincia Provincia
        {
            get
            {
                return this.ProvinciaField;
            }
            set
            {
                this.ProvinciaField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name = "ListaDistrito", Namespace = "http://schemas.datacontract.org/2004/07/Slin.Facturacion.BusinessEntities", ItemName = "Distrito")]
    public class ListaDistrito : System.Collections.Generic.List<Slin.Facturacion.Proxies.ServicioMantenimiento.Distrito>
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Pais", Namespace = "http://schemas.datacontract.org/2004/07/Slin.Facturacion.BusinessEntities")]
    public partial class Pais : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string CodigoField;

        private string DescripcionField;

        private int IdPaisField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPais
        {
            get
            {
                return this.IdPaisField;
            }
            set
            {
                this.IdPaisField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name = "ListaProvincia", Namespace = "http://schemas.datacontract.org/2004/07/Slin.Facturacion.BusinessEntities", ItemName = "Provincia")]
    public class ListaProvincia : System.Collections.Generic.List<Slin.Facturacion.Proxies.ServicioMantenimiento.Provincia>
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name = "ListaTipoDocumentoIdentidad", Namespace = "http://schemas.datacontract.org/2004/07/Slin.Facturacion.BusinessEntities", ItemName = "TipoDocumentoIdentidad")]
    public class ListaTipoDocumentoIdentidad : System.Collections.Generic.List<Slin.Facturacion.Proxies.ServicioMantenimiento.TipoDocumentoIdentidad>
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name = "ListaPais", Namespace = "http://schemas.datacontract.org/2004/07/Slin.Facturacion.BusinessEntities", ItemName = "Pais")]
    public class ListaPais : System.Collections.Generic.List<Slin.Facturacion.Proxies.ServicioMantenimiento.Pais>
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name = "ListaDepartamento", Namespace = "http://schemas.datacontract.org/2004/07/Slin.Facturacion.BusinessEntities", ItemName = "Departamento")]
    public class ListaDepartamento : System.Collections.Generic.List<Slin.Facturacion.Proxies.ServicioMantenimiento.Departamento>
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Empleado", Namespace = "http://schemas.datacontract.org/2004/07/Slin.Facturacion.BusinessEntities")]
    public partial class Empleado : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string ApeMaternoField;

        private string ApePaternoField;

        private string CelularField;

        private string CodEmpleadoField;

        private string DNIField;

        private string DireccionField;

        private string EmailField;

        private Slin.Facturacion.Proxies.ServicioMantenimiento.Empresa EmpresaField;

        private Slin.Facturacion.Proxies.ServicioMantenimiento.Estado EstadoField;

        private System.DateTime FechaNacimientoField;

        private System.DateTime FechaRegistroField;

        private int IdEmpleadoField;

        private string NombresField;

        private string NombresApellidosField;

        private int NroField;

        private Slin.Facturacion.Proxies.ServicioMantenimiento.Sexo SexoField;

        private string TelefonoField;

        private Slin.Facturacion.Proxies.ServicioMantenimiento.TipoDocumentoIdentidad TipoDocumentoIdentidadField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApeMaterno
        {
            get
            {
                return this.ApeMaternoField;
            }
            set
            {
                this.ApeMaternoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApePaterno
        {
            get
            {
                return this.ApePaternoField;
            }
            set
            {
                this.ApePaternoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Celular
        {
            get
            {
                return this.CelularField;
            }
            set
            {
                this.CelularField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodEmpleado
        {
            get
            {
                return this.CodEmpleadoField;
            }
            set
            {
                this.CodEmpleadoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DNI
        {
            get
            {
                return this.DNIField;
            }
            set
            {
                this.DNIField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion
        {
            get
            {
                return this.DireccionField;
            }
            set
            {
                this.DireccionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Slin.Facturacion.Proxies.ServicioMantenimiento.Empresa Empresa
        {
            get
            {
                return this.EmpresaField;
            }
            set
            {
                this.EmpresaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Slin.Facturacion.Proxies.ServicioMantenimiento.Estado Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaNacimiento
        {
            get
            {
                return this.FechaNacimientoField;
            }
            set
            {
                this.FechaNacimientoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaRegistro
        {
            get
            {
                return this.FechaRegistroField;
            }
            set
            {
                this.FechaRegistroField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEmpleado
        {
            get
            {
                return this.IdEmpleadoField;
            }
            set
            {
                this.IdEmpleadoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres
        {
            get
            {
                return this.NombresField;
            }
            set
            {
                this.NombresField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombresApellidos
        {
            get
            {
                return this.NombresApellidosField;
            }
            set
            {
                this.NombresApellidosField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Nro
        {
            get
            {
                return this.NroField;
            }
            set
            {
                this.NroField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Slin.Facturacion.Proxies.ServicioMantenimiento.Sexo Sexo
        {
            get
            {
                return this.SexoField;
            }
            set
            {
                this.SexoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono
        {
            get
            {
                return this.TelefonoField;
            }
            set
            {
                this.TelefonoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Slin.Facturacion.Proxies.ServicioMantenimiento.TipoDocumentoIdentidad TipoDocumentoIdentidad
        {
            get
            {
                return this.TipoDocumentoIdentidadField;
            }
            set
            {
                this.TipoDocumentoIdentidadField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name = "ListaEmpleados", Namespace = "http://schemas.datacontract.org/2004/07/Slin.Facturacion.BusinessEntities", ItemName = "Empleado")]
    public class ListaEmpleados : System.Collections.Generic.List<Slin.Facturacion.Proxies.ServicioMantenimiento.Empleado>
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name = "ListaCliente", Namespace = "http://schemas.datacontract.org/2004/07/Slin.Facturacion.BusinessEntities", ItemName = "Cliente")]
    public class ListaCliente : System.Collections.Generic.List<Slin.Facturacion.Proxies.ServicioMantenimiento.Cliente>
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Cliente", Namespace = "http://schemas.datacontract.org/2004/07/Slin.Facturacion.BusinessEntities")]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string ApellidosField;

        private string ClienteRucField;

        private string CodPaisField;

        private string CodUbigeoField;

        private string CodigoClienteField;

        private string DepartamentoField;

        private string DescripcionField;

        private string DireccionField;

        private string DistritoField;

        private string EmailField;

        private Slin.Facturacion.Proxies.ServicioMantenimiento.Email EmailClientField;

        private Slin.Facturacion.Proxies.ServicioMantenimiento.Empresa EmpresaField;

        private Slin.Facturacion.Proxies.ServicioMantenimiento.Estado EstadoField;

        private int IdClienteField;

        private string NombresField;

        private string NroDocumentoField;

        private string NumeroDocumentoIdentidadField;

        private string ProvinciaField;

        private string RazonSocialField;

        private string TelefonoField;

        private Slin.Facturacion.Proxies.ServicioMantenimiento.TipoDocumentoIdentidad TipoDocumentoIdentidadField;

        private string UrbanizacionField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellidos
        {
            get
            {
                return this.ApellidosField;
            }
            set
            {
                this.ApellidosField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClienteRuc
        {
            get
            {
                return this.ClienteRucField;
            }
            set
            {
                this.ClienteRucField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodPais
        {
            get
            {
                return this.CodPaisField;
            }
            set
            {
                this.CodPaisField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodUbigeo
        {
            get
            {
                return this.CodUbigeoField;
            }
            set
            {
                this.CodUbigeoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoCliente
        {
            get
            {
                return this.CodigoClienteField;
            }
            set
            {
                this.CodigoClienteField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Departamento
        {
            get
            {
                return this.DepartamentoField;
            }
            set
            {
                this.DepartamentoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion
        {
            get
            {
                return this.DireccionField;
            }
            set
            {
                this.DireccionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Distrito
        {
            get
            {
                return this.DistritoField;
            }
            set
            {
                this.DistritoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Slin.Facturacion.Proxies.ServicioMantenimiento.Email EmailClient
        {
            get
            {
                return this.EmailClientField;
            }
            set
            {
                this.EmailClientField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Slin.Facturacion.Proxies.ServicioMantenimiento.Empresa Empresa
        {
            get
            {
                return this.EmpresaField;
            }
            set
            {
                this.EmpresaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Slin.Facturacion.Proxies.ServicioMantenimiento.Estado Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCliente
        {
            get
            {
                return this.IdClienteField;
            }
            set
            {
                this.IdClienteField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres
        {
            get
            {
                return this.NombresField;
            }
            set
            {
                this.NombresField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NroDocumento
        {
            get
            {
                return this.NroDocumentoField;
            }
            set
            {
                this.NroDocumentoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroDocumentoIdentidad
        {
            get
            {
                return this.NumeroDocumentoIdentidadField;
            }
            set
            {
                this.NumeroDocumentoIdentidadField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Provincia
        {
            get
            {
                return this.ProvinciaField;
            }
            set
            {
                this.ProvinciaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RazonSocial
        {
            get
            {
                return this.RazonSocialField;
            }
            set
            {
                this.RazonSocialField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono
        {
            get
            {
                return this.TelefonoField;
            }
            set
            {
                this.TelefonoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Slin.Facturacion.Proxies.ServicioMantenimiento.TipoDocumentoIdentidad TipoDocumentoIdentidad
        {
            get
            {
                return this.TipoDocumentoIdentidadField;
            }
            set
            {
                this.TipoDocumentoIdentidadField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Urbanizacion
        {
            get
            {
                return this.UrbanizacionField;
            }
            set
            {
                this.UrbanizacionField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Email", Namespace = "http://schemas.datacontract.org/2004/07/Slin.Facturacion.BusinessEntities")]
    public partial class Email : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string CCField;

        private string CCOField;

        private string DescriptionField;

        private string ParaField;

        private string TypeMailField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CC
        {
            get
            {
                return this.CCField;
            }
            set
            {
                this.CCField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CCO
        {
            get
            {
                return this.CCOField;
            }
            set
            {
                this.CCOField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Para
        {
            get
            {
                return this.ParaField;
            }
            set
            {
                this.ParaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TypeMail
        {
            get
            {
                return this.TypeMailField;
            }
            set
            {
                this.TypeMailField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Bank", Namespace = "http://schemas.datacontract.org/2004/07/Slin.Facturacion.BusinessEntities")]
    public partial class Bank : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string BankNameField;

        private string CodeField;

        private string CtaDolaresField;

        private string CtaSolesField;

        private Slin.Facturacion.Proxies.ServicioMantenimiento.Empresa EmpresaField;

        private Slin.Facturacion.Proxies.ServicioMantenimiento.Estado EstadoField;

        private int IdField;

        private int TypeBankField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankName
        {
            get
            {
                return this.BankNameField;
            }
            set
            {
                this.BankNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CtaDolares
        {
            get
            {
                return this.CtaDolaresField;
            }
            set
            {
                this.CtaDolaresField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CtaSoles
        {
            get
            {
                return this.CtaSolesField;
            }
            set
            {
                this.CtaSolesField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Slin.Facturacion.Proxies.ServicioMantenimiento.Empresa Empresa
        {
            get
            {
                return this.EmpresaField;
            }
            set
            {
                this.EmpresaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Slin.Facturacion.Proxies.ServicioMantenimiento.Estado Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TypeBank
        {
            get
            {
                return this.TypeBankField;
            }
            set
            {
                this.TypeBankField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name = "ListBank", Namespace = "http://schemas.datacontract.org/2004/07/Slin.Facturacion.BusinessEntities", ItemName = "Bank")]
    public class ListBank : System.Collections.Generic.List<Slin.Facturacion.Proxies.ServicioMantenimiento.Bank>
    {
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "Slin.Facturacion.Proxies.ServicioMantenimiento.IServicioMantenimiento")]
    public interface IServicioMantenimiento
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioMantenimiento/GetListaSexo", ReplyAction = "http://tempuri.org/IServicioMantenimiento/GetListaSexoResponse")]
        Slin.Facturacion.Proxies.ServicioMantenimiento.ListaSexo GetListaSexo();

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioMantenimiento/GetListaSexo", ReplyAction = "http://tempuri.org/IServicioMantenimiento/GetListaSexoResponse")]
        System.Threading.Tasks.Task<Slin.Facturacion.Proxies.ServicioMantenimiento.ListaSexo> GetListaSexoAsync();

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioMantenimiento/GetListaEstado", ReplyAction = "http://tempuri.org/IServicioMantenimiento/GetListaEstadoResponse")]
        Slin.Facturacion.Proxies.ServicioMantenimiento.ListaEstado GetListaEstado();

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioMantenimiento/GetListaEstado", ReplyAction = "http://tempuri.org/IServicioMantenimiento/GetListaEstadoResponse")]
        System.Threading.Tasks.Task<Slin.Facturacion.Proxies.ServicioMantenimiento.ListaEstado> GetListaEstadoAsync();

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioMantenimiento/GetListaEmpresa", ReplyAction = "http://tempuri.org/IServicioMantenimiento/GetListaEmpresaResponse")]
        Slin.Facturacion.Proxies.ServicioMantenimiento.ListaEmpresa GetListaEmpresa();

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioMantenimiento/GetListaEmpresa", ReplyAction = "http://tempuri.org/IServicioMantenimiento/GetListaEmpresaResponse")]
        System.Threading.Tasks.Task<Slin.Facturacion.Proxies.ServicioMantenimiento.ListaEmpresa> GetListaEmpresaAsync();

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioMantenimiento/GetListaTipoDocumentoIdentidad", ReplyAction = "http://tempuri.org/IServicioMantenimiento/GetListaTipoDocumentoIdentidadResponse")]
        Slin.Facturacion.Proxies.ServicioMantenimiento.ListaTipoDocumentoIdentidad GetListaTipoDocumentoIdentidad();

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioMantenimiento/GetListaTipoDocumentoIdentidad", ReplyAction = "http://tempuri.org/IServicioMantenimiento/GetListaTipoDocumentoIdentidadResponse")]
        System.Threading.Tasks.Task<Slin.Facturacion.Proxies.ServicioMantenimiento.ListaTipoDocumentoIdentidad> GetListaTipoDocumentoIdentidadAsync();

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioMantenimiento/GetListaPais", ReplyAction = "http://tempuri.org/IServicioMantenimiento/GetListaPaisResponse")]
        Slin.Facturacion.Proxies.ServicioMantenimiento.ListaPais GetListaPais();

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioMantenimiento/GetListaPais", ReplyAction = "http://tempuri.org/IServicioMantenimiento/GetListaPaisResponse")]
        System.Threading.Tasks.Task<Slin.Facturacion.Proxies.ServicioMantenimiento.ListaPais> GetListaPaisAsync();

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioMantenimiento/GetListaDepartamento", ReplyAction = "http://tempuri.org/IServicioMantenimiento/GetListaDepartamentoResponse")]
        Slin.Facturacion.Proxies.ServicioMantenimiento.ListaDepartamento GetListaDepartamento(int IdPais);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioMantenimiento/GetListaDepartamento", ReplyAction = "http://tempuri.org/IServicioMantenimiento/GetListaDepartamentoResponse")]
        System.Threading.Tasks.Task<Slin.Facturacion.Proxies.ServicioMantenimiento.ListaDepartamento> GetListaDepartamentoAsync(int IdPais);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioMantenimiento/GetListaProvincia", ReplyAction = "http://tempuri.org/IServicioMantenimiento/GetListaProvinciaResponse")]
        Slin.Facturacion.Proxies.ServicioMantenimiento.ListaProvincia GetListaProvincia(int IdDepartamento);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioMantenimiento/GetListaProvincia", ReplyAction = "http://tempuri.org/IServicioMantenimiento/GetListaProvinciaResponse")]
        System.Threading.Tasks.Task<Slin.Facturacion.Proxies.ServicioMantenimiento.ListaProvincia> GetListaProvinciaAsync(int IdDepartamento);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioMantenimiento/GetListaDistrito", ReplyAction = "http://tempuri.org/IServicioMantenimiento/GetListaDistritoResponse")]
        Slin.Facturacion.Proxies.ServicioMantenimiento.ListaDistrito GetListaDistrito(int IdProvincia);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioMantenimiento/GetListaDistrito", ReplyAction = "http://tempuri.org/IServicioMantenimiento/GetListaDistritoResponse")]
        System.Threading.Tasks.Task<Slin.Facturacion.Proxies.ServicioMantenimiento.ListaDistrito> GetListaDistritoAsync(int IdProvincia);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioMantenimiento/GetListaEmpleado", ReplyAction = "http://tempuri.org/IServicioMantenimiento/GetListaEmpleadoResponse")]
        Slin.Facturacion.Proxies.ServicioMantenimiento.ListaEmpleados GetListaEmpleado(Slin.Facturacion.Proxies.ServicioMantenimiento.Empleado oEmpleado);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioMantenimiento/GetListaEmpleado", ReplyAction = "http://tempuri.org/IServicioMantenimiento/GetListaEmpleadoResponse")]
        System.Threading.Tasks.Task<Slin.Facturacion.Proxies.ServicioMantenimiento.ListaEmpleados> GetListaEmpleadoAsync(Slin.Facturacion.Proxies.ServicioMantenimiento.Empleado oEmpleado);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioMantenimiento/GetListadoEmpresa", ReplyAction = "http://tempuri.org/IServicioMantenimiento/GetListadoEmpresaResponse")]
        Slin.Facturacion.Proxies.ServicioMantenimiento.ListaEmpresa GetListadoEmpresa(Slin.Facturacion.Proxies.ServicioMantenimiento.Empresa oEmpresa);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioMantenimiento/GetListadoEmpresa", ReplyAction = "http://tempuri.org/IServicioMantenimiento/GetListadoEmpresaResponse")]
        System.Threading.Tasks.Task<Slin.Facturacion.Proxies.ServicioMantenimiento.ListaEmpresa> GetListadoEmpresaAsync(Slin.Facturacion.Proxies.ServicioMantenimiento.Empresa oEmpresa);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioMantenimiento/RegistrarEmpleado", ReplyAction = "http://tempuri.org/IServicioMantenimiento/RegistrarEmpleadoResponse")]
        string RegistrarEmpleado(Slin.Facturacion.Proxies.ServicioMantenimiento.Empleado oEmpleado);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioMantenimiento/RegistrarEmpleado", ReplyAction = "http://tempuri.org/IServicioMantenimiento/RegistrarEmpleadoResponse")]
        System.Threading.Tasks.Task<string> RegistrarEmpleadoAsync(Slin.Facturacion.Proxies.ServicioMantenimiento.Empleado oEmpleado);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioMantenimiento/ActualizarEmpleado", ReplyAction = "http://tempuri.org/IServicioMantenimiento/ActualizarEmpleadoResponse")]
        string ActualizarEmpleado(Slin.Facturacion.Proxies.ServicioMantenimiento.Empleado oEmpleado);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioMantenimiento/ActualizarEmpleado", ReplyAction = "http://tempuri.org/IServicioMantenimiento/ActualizarEmpleadoResponse")]
        System.Threading.Tasks.Task<string> ActualizarEmpleadoAsync(Slin.Facturacion.Proxies.ServicioMantenimiento.Empleado oEmpleado);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioMantenimiento/ValidarDniRuc", ReplyAction = "http://tempuri.org/IServicioMantenimiento/ValidarDniRucResponse")]
        int ValidarDniRuc(string Dni_Ruc);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioMantenimiento/ValidarDniRuc", ReplyAction = "http://tempuri.org/IServicioMantenimiento/ValidarDniRucResponse")]
        System.Threading.Tasks.Task<int> ValidarDniRucAsync(string Dni_Ruc);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioMantenimiento/ValidarEmpresaRuc", ReplyAction = "http://tempuri.org/IServicioMantenimiento/ValidarEmpresaRucResponse")]
        Slin.Facturacion.Proxies.ServicioMantenimiento.ListaEmpresa ValidarEmpresaRuc(string Ruc_Empresa);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioMantenimiento/ValidarEmpresaRuc", ReplyAction = "http://tempuri.org/IServicioMantenimiento/ValidarEmpresaRucResponse")]
        System.Threading.Tasks.Task<Slin.Facturacion.Proxies.ServicioMantenimiento.ListaEmpresa> ValidarEmpresaRucAsync(string Ruc_Empresa);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioMantenimiento/RegistrarEmpresa", ReplyAction = "http://tempuri.org/IServicioMantenimiento/RegistrarEmpresaResponse")]
        string RegistrarEmpresa(Slin.Facturacion.Proxies.ServicioMantenimiento.Empresa oEmpresa);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioMantenimiento/RegistrarEmpresa", ReplyAction = "http://tempuri.org/IServicioMantenimiento/RegistrarEmpresaResponse")]
        System.Threading.Tasks.Task<string> RegistrarEmpresaAsync(Slin.Facturacion.Proxies.ServicioMantenimiento.Empresa oEmpresa);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioMantenimiento/ActualizarEmpresa", ReplyAction = "http://tempuri.org/IServicioMantenimiento/ActualizarEmpresaResponse")]
        string ActualizarEmpresa(Slin.Facturacion.Proxies.ServicioMantenimiento.Empresa oEmpresa);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioMantenimiento/ActualizarEmpresa", ReplyAction = "http://tempuri.org/IServicioMantenimiento/ActualizarEmpresaResponse")]
        System.Threading.Tasks.Task<string> ActualizarEmpresaAsync(Slin.Facturacion.Proxies.ServicioMantenimiento.Empresa oEmpresa);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioMantenimiento/GetUbigeo", ReplyAction = "http://tempuri.org/IServicioMantenimiento/GetUbigeoResponse")]
        Slin.Facturacion.Proxies.ServicioMantenimiento.Ubigeo GetUbigeo(string CodigoUbigeo);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioMantenimiento/GetUbigeo", ReplyAction = "http://tempuri.org/IServicioMantenimiento/GetUbigeoResponse")]
        System.Threading.Tasks.Task<Slin.Facturacion.Proxies.ServicioMantenimiento.Ubigeo> GetUbigeoAsync(string CodigoUbigeo);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioMantenimiento/ValidarNroClienteExiste", ReplyAction = "http://tempuri.org/IServicioMantenimiento/ValidarNroClienteExisteResponse")]
        Slin.Facturacion.Proxies.ServicioMantenimiento.ListaCliente ValidarNroClienteExiste(string NroDocumento);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioMantenimiento/ValidarNroClienteExiste", ReplyAction = "http://tempuri.org/IServicioMantenimiento/ValidarNroClienteExisteResponse")]
        System.Threading.Tasks.Task<Slin.Facturacion.Proxies.ServicioMantenimiento.ListaCliente> ValidarNroClienteExisteAsync(string NroDocumento);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioMantenimiento/InsertarCliente", ReplyAction = "http://tempuri.org/IServicioMantenimiento/InsertarClienteResponse")]
        string InsertarCliente(Slin.Facturacion.Proxies.ServicioMantenimiento.Cliente oCliente);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioMantenimiento/InsertarCliente", ReplyAction = "http://tempuri.org/IServicioMantenimiento/InsertarClienteResponse")]
        System.Threading.Tasks.Task<string> InsertarClienteAsync(Slin.Facturacion.Proxies.ServicioMantenimiento.Cliente oCliente);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioMantenimiento/ActualizarCliente", ReplyAction = "http://tempuri.org/IServicioMantenimiento/ActualizarClienteResponse")]
        string ActualizarCliente(Slin.Facturacion.Proxies.ServicioMantenimiento.Cliente oCliente);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioMantenimiento/ActualizarCliente", ReplyAction = "http://tempuri.org/IServicioMantenimiento/ActualizarClienteResponse")]
        System.Threading.Tasks.Task<string> ActualizarClienteAsync(Slin.Facturacion.Proxies.ServicioMantenimiento.Cliente oCliente);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioMantenimiento/GetListaCliente", ReplyAction = "http://tempuri.org/IServicioMantenimiento/GetListaClienteResponse")]
        Slin.Facturacion.Proxies.ServicioMantenimiento.ListaCliente GetListaCliente(Slin.Facturacion.Proxies.ServicioMantenimiento.Cliente oCliente);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioMantenimiento/GetListaCliente", ReplyAction = "http://tempuri.org/IServicioMantenimiento/GetListaClienteResponse")]
        System.Threading.Tasks.Task<Slin.Facturacion.Proxies.ServicioMantenimiento.ListaCliente> GetListaClienteAsync(Slin.Facturacion.Proxies.ServicioMantenimiento.Cliente oCliente);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioMantenimiento/Insert_CtaBank", ReplyAction = "http://tempuri.org/IServicioMantenimiento/Insert_CtaBankResponse")]
        string Insert_CtaBank(Slin.Facturacion.Proxies.ServicioMantenimiento.Bank objbank);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioMantenimiento/Insert_CtaBank", ReplyAction = "http://tempuri.org/IServicioMantenimiento/Insert_CtaBankResponse")]
        System.Threading.Tasks.Task<string> Insert_CtaBankAsync(Slin.Facturacion.Proxies.ServicioMantenimiento.Bank objbank);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioMantenimiento/Update_CtaBank", ReplyAction = "http://tempuri.org/IServicioMantenimiento/Update_CtaBankResponse")]
        string Update_CtaBank(Slin.Facturacion.Proxies.ServicioMantenimiento.Bank objbank);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioMantenimiento/Update_CtaBank", ReplyAction = "http://tempuri.org/IServicioMantenimiento/Update_CtaBankResponse")]
        System.Threading.Tasks.Task<string> Update_CtaBankAsync(Slin.Facturacion.Proxies.ServicioMantenimiento.Bank objbank);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioMantenimiento/GetListBank", ReplyAction = "http://tempuri.org/IServicioMantenimiento/GetListBankResponse")]
        Slin.Facturacion.Proxies.ServicioMantenimiento.ListBank GetListBank(string RucEntity);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioMantenimiento/GetListBank", ReplyAction = "http://tempuri.org/IServicioMantenimiento/GetListBankResponse")]
        System.Threading.Tasks.Task<Slin.Facturacion.Proxies.ServicioMantenimiento.ListBank> GetListBankAsync(string RucEntity);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioMantenimiento/Get_ListCompanyGroup", ReplyAction = "http://tempuri.org/IServicioMantenimiento/Get_ListCompanyGroupResponse")]
        Slin.Facturacion.Proxies.ServicioMantenimiento.ListaEmpresa Get_ListCompanyGroup(int Grp);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioMantenimiento/Get_ListCompanyGroup", ReplyAction = "http://tempuri.org/IServicioMantenimiento/Get_ListCompanyGroupResponse")]
        System.Threading.Tasks.Task<Slin.Facturacion.Proxies.ServicioMantenimiento.ListaEmpresa> Get_ListCompanyGroupAsync(int Grp);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioMantenimientoChannel : Slin.Facturacion.Proxies.ServicioMantenimiento.IServicioMantenimiento, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioMantenimientoClient : System.ServiceModel.ClientBase<Slin.Facturacion.Proxies.ServicioMantenimiento.IServicioMantenimiento>, Slin.Facturacion.Proxies.ServicioMantenimiento.IServicioMantenimiento
    {

        public ServicioMantenimientoClient()
        {
        }

        public ServicioMantenimientoClient(string endpointConfigurationName) :
                base(endpointConfigurationName)
        {
        }

        public ServicioMantenimientoClient(string endpointConfigurationName, string remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public ServicioMantenimientoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public ServicioMantenimientoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        public Slin.Facturacion.Proxies.ServicioMantenimiento.ListaSexo GetListaSexo()
        {
            return base.Channel.GetListaSexo();
        }

        public System.Threading.Tasks.Task<Slin.Facturacion.Proxies.ServicioMantenimiento.ListaSexo> GetListaSexoAsync()
        {
            return base.Channel.GetListaSexoAsync();
        }

        public Slin.Facturacion.Proxies.ServicioMantenimiento.ListaEstado GetListaEstado()
        {
            return base.Channel.GetListaEstado();
        }

        public System.Threading.Tasks.Task<Slin.Facturacion.Proxies.ServicioMantenimiento.ListaEstado> GetListaEstadoAsync()
        {
            return base.Channel.GetListaEstadoAsync();
        }

        public Slin.Facturacion.Proxies.ServicioMantenimiento.ListaEmpresa GetListaEmpresa()
        {
            return base.Channel.GetListaEmpresa();
        }

        public System.Threading.Tasks.Task<Slin.Facturacion.Proxies.ServicioMantenimiento.ListaEmpresa> GetListaEmpresaAsync()
        {
            return base.Channel.GetListaEmpresaAsync();
        }

        public Slin.Facturacion.Proxies.ServicioMantenimiento.ListaTipoDocumentoIdentidad GetListaTipoDocumentoIdentidad()
        {
            return base.Channel.GetListaTipoDocumentoIdentidad();
        }

        public System.Threading.Tasks.Task<Slin.Facturacion.Proxies.ServicioMantenimiento.ListaTipoDocumentoIdentidad> GetListaTipoDocumentoIdentidadAsync()
        {
            return base.Channel.GetListaTipoDocumentoIdentidadAsync();
        }

        public Slin.Facturacion.Proxies.ServicioMantenimiento.ListaPais GetListaPais()
        {
            return base.Channel.GetListaPais();
        }

        public System.Threading.Tasks.Task<Slin.Facturacion.Proxies.ServicioMantenimiento.ListaPais> GetListaPaisAsync()
        {
            return base.Channel.GetListaPaisAsync();
        }

        public Slin.Facturacion.Proxies.ServicioMantenimiento.ListaDepartamento GetListaDepartamento(int IdPais)
        {
            return base.Channel.GetListaDepartamento(IdPais);
        }

        public System.Threading.Tasks.Task<Slin.Facturacion.Proxies.ServicioMantenimiento.ListaDepartamento> GetListaDepartamentoAsync(int IdPais)
        {
            return base.Channel.GetListaDepartamentoAsync(IdPais);
        }

        public Slin.Facturacion.Proxies.ServicioMantenimiento.ListaProvincia GetListaProvincia(int IdDepartamento)
        {
            return base.Channel.GetListaProvincia(IdDepartamento);
        }

        public System.Threading.Tasks.Task<Slin.Facturacion.Proxies.ServicioMantenimiento.ListaProvincia> GetListaProvinciaAsync(int IdDepartamento)
        {
            return base.Channel.GetListaProvinciaAsync(IdDepartamento);
        }

        public Slin.Facturacion.Proxies.ServicioMantenimiento.ListaDistrito GetListaDistrito(int IdProvincia)
        {
            return base.Channel.GetListaDistrito(IdProvincia);
        }

        public System.Threading.Tasks.Task<Slin.Facturacion.Proxies.ServicioMantenimiento.ListaDistrito> GetListaDistritoAsync(int IdProvincia)
        {
            return base.Channel.GetListaDistritoAsync(IdProvincia);
        }

        public Slin.Facturacion.Proxies.ServicioMantenimiento.ListaEmpleados GetListaEmpleado(Slin.Facturacion.Proxies.ServicioMantenimiento.Empleado oEmpleado)
        {
            return base.Channel.GetListaEmpleado(oEmpleado);
        }

        public System.Threading.Tasks.Task<Slin.Facturacion.Proxies.ServicioMantenimiento.ListaEmpleados> GetListaEmpleadoAsync(Slin.Facturacion.Proxies.ServicioMantenimiento.Empleado oEmpleado)
        {
            return base.Channel.GetListaEmpleadoAsync(oEmpleado);
        }

        public Slin.Facturacion.Proxies.ServicioMantenimiento.ListaEmpresa GetListadoEmpresa(Slin.Facturacion.Proxies.ServicioMantenimiento.Empresa oEmpresa)
        {
            return base.Channel.GetListadoEmpresa(oEmpresa);
        }

        public System.Threading.Tasks.Task<Slin.Facturacion.Proxies.ServicioMantenimiento.ListaEmpresa> GetListadoEmpresaAsync(Slin.Facturacion.Proxies.ServicioMantenimiento.Empresa oEmpresa)
        {
            return base.Channel.GetListadoEmpresaAsync(oEmpresa);
        }

        public string RegistrarEmpleado(Slin.Facturacion.Proxies.ServicioMantenimiento.Empleado oEmpleado)
        {
            return base.Channel.RegistrarEmpleado(oEmpleado);
        }

        public System.Threading.Tasks.Task<string> RegistrarEmpleadoAsync(Slin.Facturacion.Proxies.ServicioMantenimiento.Empleado oEmpleado)
        {
            return base.Channel.RegistrarEmpleadoAsync(oEmpleado);
        }

        public string ActualizarEmpleado(Slin.Facturacion.Proxies.ServicioMantenimiento.Empleado oEmpleado)
        {
            return base.Channel.ActualizarEmpleado(oEmpleado);
        }

        public System.Threading.Tasks.Task<string> ActualizarEmpleadoAsync(Slin.Facturacion.Proxies.ServicioMantenimiento.Empleado oEmpleado)
        {
            return base.Channel.ActualizarEmpleadoAsync(oEmpleado);
        }

        public int ValidarDniRuc(string Dni_Ruc)
        {
            return base.Channel.ValidarDniRuc(Dni_Ruc);
        }

        public System.Threading.Tasks.Task<int> ValidarDniRucAsync(string Dni_Ruc)
        {
            return base.Channel.ValidarDniRucAsync(Dni_Ruc);
        }

        public Slin.Facturacion.Proxies.ServicioMantenimiento.ListaEmpresa ValidarEmpresaRuc(string Ruc_Empresa)
        {
            return base.Channel.ValidarEmpresaRuc(Ruc_Empresa);
        }

        public System.Threading.Tasks.Task<Slin.Facturacion.Proxies.ServicioMantenimiento.ListaEmpresa> ValidarEmpresaRucAsync(string Ruc_Empresa)
        {
            return base.Channel.ValidarEmpresaRucAsync(Ruc_Empresa);
        }

        public string RegistrarEmpresa(Slin.Facturacion.Proxies.ServicioMantenimiento.Empresa oEmpresa)
        {
            return base.Channel.RegistrarEmpresa(oEmpresa);
        }

        public System.Threading.Tasks.Task<string> RegistrarEmpresaAsync(Slin.Facturacion.Proxies.ServicioMantenimiento.Empresa oEmpresa)
        {
            return base.Channel.RegistrarEmpresaAsync(oEmpresa);
        }

        public string ActualizarEmpresa(Slin.Facturacion.Proxies.ServicioMantenimiento.Empresa oEmpresa)
        {
            return base.Channel.ActualizarEmpresa(oEmpresa);
        }

        public System.Threading.Tasks.Task<string> ActualizarEmpresaAsync(Slin.Facturacion.Proxies.ServicioMantenimiento.Empresa oEmpresa)
        {
            return base.Channel.ActualizarEmpresaAsync(oEmpresa);
        }

        public Slin.Facturacion.Proxies.ServicioMantenimiento.Ubigeo GetUbigeo(string CodigoUbigeo)
        {
            return base.Channel.GetUbigeo(CodigoUbigeo);
        }

        public System.Threading.Tasks.Task<Slin.Facturacion.Proxies.ServicioMantenimiento.Ubigeo> GetUbigeoAsync(string CodigoUbigeo)
        {
            return base.Channel.GetUbigeoAsync(CodigoUbigeo);
        }

        public Slin.Facturacion.Proxies.ServicioMantenimiento.ListaCliente ValidarNroClienteExiste(string NroDocumento)
        {
            return base.Channel.ValidarNroClienteExiste(NroDocumento);
        }

        public System.Threading.Tasks.Task<Slin.Facturacion.Proxies.ServicioMantenimiento.ListaCliente> ValidarNroClienteExisteAsync(string NroDocumento)
        {
            return base.Channel.ValidarNroClienteExisteAsync(NroDocumento);
        }

        public string InsertarCliente(Slin.Facturacion.Proxies.ServicioMantenimiento.Cliente oCliente)
        {
            return base.Channel.InsertarCliente(oCliente);
        }

        public System.Threading.Tasks.Task<string> InsertarClienteAsync(Slin.Facturacion.Proxies.ServicioMantenimiento.Cliente oCliente)
        {
            return base.Channel.InsertarClienteAsync(oCliente);
        }

        public string ActualizarCliente(Slin.Facturacion.Proxies.ServicioMantenimiento.Cliente oCliente)
        {
            return base.Channel.ActualizarCliente(oCliente);
        }

        public System.Threading.Tasks.Task<string> ActualizarClienteAsync(Slin.Facturacion.Proxies.ServicioMantenimiento.Cliente oCliente)
        {
            return base.Channel.ActualizarClienteAsync(oCliente);
        }

        public Slin.Facturacion.Proxies.ServicioMantenimiento.ListaCliente GetListaCliente(Slin.Facturacion.Proxies.ServicioMantenimiento.Cliente oCliente)
        {
            return base.Channel.GetListaCliente(oCliente);
        }

        public System.Threading.Tasks.Task<Slin.Facturacion.Proxies.ServicioMantenimiento.ListaCliente> GetListaClienteAsync(Slin.Facturacion.Proxies.ServicioMantenimiento.Cliente oCliente)
        {
            return base.Channel.GetListaClienteAsync(oCliente);
        }

        public string Insert_CtaBank(Slin.Facturacion.Proxies.ServicioMantenimiento.Bank objbank)
        {
            return base.Channel.Insert_CtaBank(objbank);
        }

        public System.Threading.Tasks.Task<string> Insert_CtaBankAsync(Slin.Facturacion.Proxies.ServicioMantenimiento.Bank objbank)
        {
            return base.Channel.Insert_CtaBankAsync(objbank);
        }

        public string Update_CtaBank(Slin.Facturacion.Proxies.ServicioMantenimiento.Bank objbank)
        {
            return base.Channel.Update_CtaBank(objbank);
        }

        public System.Threading.Tasks.Task<string> Update_CtaBankAsync(Slin.Facturacion.Proxies.ServicioMantenimiento.Bank objbank)
        {
            return base.Channel.Update_CtaBankAsync(objbank);
        }

        public Slin.Facturacion.Proxies.ServicioMantenimiento.ListBank GetListBank(string RucEntity)
        {
            return base.Channel.GetListBank(RucEntity);
        }

        public System.Threading.Tasks.Task<Slin.Facturacion.Proxies.ServicioMantenimiento.ListBank> GetListBankAsync(string RucEntity)
        {
            return base.Channel.GetListBankAsync(RucEntity);
        }

        public Slin.Facturacion.Proxies.ServicioMantenimiento.ListaEmpresa Get_ListCompanyGroup(int Grp)
        {
            return base.Channel.Get_ListCompanyGroup(Grp);
        }

        public System.Threading.Tasks.Task<Slin.Facturacion.Proxies.ServicioMantenimiento.ListaEmpresa> Get_ListCompanyGroupAsync(int Grp)
        {
            return base.Channel.Get_ListCompanyGroupAsync(Grp);
        }
    }
}
