//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Slin.Facturacion.Proxies.ServicioConfiguracion
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name = "ListaURLAmbiente", Namespace = "http://schemas.datacontract.org/2004/07/Slin.Facturacion.BusinessEntities", ItemName = "URLAmbiente")]
    public class ListaURLAmbiente : System.Collections.Generic.List<Slin.Facturacion.Proxies.ServicioConfiguracion.URLAmbiente>
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "URLAmbiente", Namespace = "http://schemas.datacontract.org/2004/07/Slin.Facturacion.BusinessEntities")]
    public partial class URLAmbiente : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private Slin.Facturacion.Proxies.ServicioConfiguracion.AmbienteSunat AmbienteSunatField;

        private string CodigoField;

        private string DescripcionField;

        private Slin.Facturacion.Proxies.ServicioConfiguracion.Estado EstadoField;

        private int IdUrlField;

        private string URLField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Slin.Facturacion.Proxies.ServicioConfiguracion.AmbienteSunat AmbienteSunat
        {
            get
            {
                return this.AmbienteSunatField;
            }
            set
            {
                this.AmbienteSunatField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Slin.Facturacion.Proxies.ServicioConfiguracion.Estado Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUrl
        {
            get
            {
                return this.IdUrlField;
            }
            set
            {
                this.IdUrlField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URL
        {
            get
            {
                return this.URLField;
            }
            set
            {
                this.URLField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "AmbienteSunat", Namespace = "http://schemas.datacontract.org/2004/07/Slin.Facturacion.BusinessEntities")]
    public partial class AmbienteSunat : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string CodigoField;

        private string DescripcionField;

        private Slin.Facturacion.Proxies.ServicioConfiguracion.Estado EstadoField;

        private int IdAmbienteField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Slin.Facturacion.Proxies.ServicioConfiguracion.Estado Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAmbiente
        {
            get
            {
                return this.IdAmbienteField;
            }
            set
            {
                this.IdAmbienteField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Estado", Namespace = "http://schemas.datacontract.org/2004/07/Slin.Facturacion.BusinessEntities")]
    public partial class Estado : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string DescripcionField;

        private int IdEstadoField;

        private int IdEstadoSUNATField;

        private string RutaImagenField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEstado
        {
            get
            {
                return this.IdEstadoField;
            }
            set
            {
                this.IdEstadoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEstadoSUNAT
        {
            get
            {
                return this.IdEstadoSUNATField;
            }
            set
            {
                this.IdEstadoSUNATField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RutaImagen
        {
            get
            {
                return this.RutaImagenField;
            }
            set
            {
                this.RutaImagenField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name = "ListaDocumentoAmbiente", Namespace = "http://schemas.datacontract.org/2004/07/Slin.Facturacion.BusinessEntities", ItemName = "DocumentoAmbiente")]
    public class ListaDocumentoAmbiente : System.Collections.Generic.List<Slin.Facturacion.Proxies.ServicioConfiguracion.DocumentoAmbiente>
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "DocumentoAmbiente", Namespace = "http://schemas.datacontract.org/2004/07/Slin.Facturacion.BusinessEntities")]
    public partial class DocumentoAmbiente : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private Slin.Facturacion.Proxies.ServicioConfiguracion.AmbienteSunat AmbienteSunatField;

        private string DESCRIPCION_TPO_CEField;

        private Slin.Facturacion.Proxies.ServicioConfiguracion.Empresa EmpresaField;

        private Slin.Facturacion.Proxies.ServicioConfiguracion.Estado EstadoField;

        private int IDField;

        private int ID_TPO_CEField;

        private string TIPO_CEField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Slin.Facturacion.Proxies.ServicioConfiguracion.AmbienteSunat AmbienteSunat
        {
            get
            {
                return this.AmbienteSunatField;
            }
            set
            {
                this.AmbienteSunatField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DESCRIPCION_TPO_CE
        {
            get
            {
                return this.DESCRIPCION_TPO_CEField;
            }
            set
            {
                this.DESCRIPCION_TPO_CEField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Slin.Facturacion.Proxies.ServicioConfiguracion.Empresa Empresa
        {
            get
            {
                return this.EmpresaField;
            }
            set
            {
                this.EmpresaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Slin.Facturacion.Proxies.ServicioConfiguracion.Estado Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_TPO_CE
        {
            get
            {
                return this.ID_TPO_CEField;
            }
            set
            {
                this.ID_TPO_CEField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TIPO_CE
        {
            get
            {
                return this.TIPO_CEField;
            }
            set
            {
                this.TIPO_CEField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Empresa", Namespace = "http://schemas.datacontract.org/2004/07/Slin.Facturacion.BusinessEntities")]
    public partial class Empresa : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string CodEmpresaField;

        private string CodPaisField;

        private string CodigoUbigeoField;

        private string DepartamentoField;

        private string DireccionField;

        private string DistritoField;

        private string DomicilioFiscalField;

        private string DominioField;

        private string EmailField;

        private Slin.Facturacion.Proxies.ServicioConfiguracion.Estado EstadoField;

        private string FaxField;

        private System.DateTime FechaRegistroField;

        private string IPField;

        private int IdEmpresaField;

        private int NroField;

        private string PaginaWebField;

        private string PasswordField;

        private int PortField;

        private string ProvinciaField;

        private string RUCField;

        private string RazonComercialField;

        private string RazonSocialField;

        private string TelefonoField;

        private Slin.Facturacion.Proxies.ServicioConfiguracion.TipoDocumentoIdentidad TipoDocumentiIdentidadField;

        private string TipoLoginField;

        private Slin.Facturacion.Proxies.ServicioConfiguracion.Ubigeo UbigeoField;

        private string UrbanizacionField;

        private string Url_CompanyConsultField;

        private string Url_CompanyLogoField;

        private int UseSSLField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodEmpresa
        {
            get
            {
                return this.CodEmpresaField;
            }
            set
            {
                this.CodEmpresaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodPais
        {
            get
            {
                return this.CodPaisField;
            }
            set
            {
                this.CodPaisField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoUbigeo
        {
            get
            {
                return this.CodigoUbigeoField;
            }
            set
            {
                this.CodigoUbigeoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Departamento
        {
            get
            {
                return this.DepartamentoField;
            }
            set
            {
                this.DepartamentoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion
        {
            get
            {
                return this.DireccionField;
            }
            set
            {
                this.DireccionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Distrito
        {
            get
            {
                return this.DistritoField;
            }
            set
            {
                this.DistritoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DomicilioFiscal
        {
            get
            {
                return this.DomicilioFiscalField;
            }
            set
            {
                this.DomicilioFiscalField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dominio
        {
            get
            {
                return this.DominioField;
            }
            set
            {
                this.DominioField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Slin.Facturacion.Proxies.ServicioConfiguracion.Estado Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fax
        {
            get
            {
                return this.FaxField;
            }
            set
            {
                this.FaxField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaRegistro
        {
            get
            {
                return this.FechaRegistroField;
            }
            set
            {
                this.FechaRegistroField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IP
        {
            get
            {
                return this.IPField;
            }
            set
            {
                this.IPField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEmpresa
        {
            get
            {
                return this.IdEmpresaField;
            }
            set
            {
                this.IdEmpresaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Nro
        {
            get
            {
                return this.NroField;
            }
            set
            {
                this.NroField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaginaWeb
        {
            get
            {
                return this.PaginaWebField;
            }
            set
            {
                this.PaginaWebField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Port
        {
            get
            {
                return this.PortField;
            }
            set
            {
                this.PortField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Provincia
        {
            get
            {
                return this.ProvinciaField;
            }
            set
            {
                this.ProvinciaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RUC
        {
            get
            {
                return this.RUCField;
            }
            set
            {
                this.RUCField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RazonComercial
        {
            get
            {
                return this.RazonComercialField;
            }
            set
            {
                this.RazonComercialField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RazonSocial
        {
            get
            {
                return this.RazonSocialField;
            }
            set
            {
                this.RazonSocialField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono
        {
            get
            {
                return this.TelefonoField;
            }
            set
            {
                this.TelefonoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Slin.Facturacion.Proxies.ServicioConfiguracion.TipoDocumentoIdentidad TipoDocumentiIdentidad
        {
            get
            {
                return this.TipoDocumentiIdentidadField;
            }
            set
            {
                this.TipoDocumentiIdentidadField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoLogin
        {
            get
            {
                return this.TipoLoginField;
            }
            set
            {
                this.TipoLoginField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Slin.Facturacion.Proxies.ServicioConfiguracion.Ubigeo Ubigeo
        {
            get
            {
                return this.UbigeoField;
            }
            set
            {
                this.UbigeoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Urbanizacion
        {
            get
            {
                return this.UrbanizacionField;
            }
            set
            {
                this.UrbanizacionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url_CompanyConsult
        {
            get
            {
                return this.Url_CompanyConsultField;
            }
            set
            {
                this.Url_CompanyConsultField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url_CompanyLogo
        {
            get
            {
                return this.Url_CompanyLogoField;
            }
            set
            {
                this.Url_CompanyLogoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UseSSL
        {
            get
            {
                return this.UseSSLField;
            }
            set
            {
                this.UseSSLField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "TipoDocumentoIdentidad", Namespace = "http://schemas.datacontract.org/2004/07/Slin.Facturacion.BusinessEntities")]
    public partial class TipoDocumentoIdentidad : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string CodigoField;

        private string DescripcionField;

        private int IdTipoDocumentoIdentidadField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTipoDocumentoIdentidad
        {
            get
            {
                return this.IdTipoDocumentoIdentidadField;
            }
            set
            {
                this.IdTipoDocumentoIdentidadField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Ubigeo", Namespace = "http://schemas.datacontract.org/2004/07/Slin.Facturacion.BusinessEntities")]
    public partial class Ubigeo : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string CodigoUbigeoField;

        private string DescripcionField;

        private Slin.Facturacion.Proxies.ServicioConfiguracion.Distrito DistritoField;

        private int IdUbigeoField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoUbigeo
        {
            get
            {
                return this.CodigoUbigeoField;
            }
            set
            {
                this.CodigoUbigeoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Slin.Facturacion.Proxies.ServicioConfiguracion.Distrito Distrito
        {
            get
            {
                return this.DistritoField;
            }
            set
            {
                this.DistritoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUbigeo
        {
            get
            {
                return this.IdUbigeoField;
            }
            set
            {
                this.IdUbigeoField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Distrito", Namespace = "http://schemas.datacontract.org/2004/07/Slin.Facturacion.BusinessEntities")]
    public partial class Distrito : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string CodigoField;

        private string CodigoUbigeoField;

        private string DescripcionField;

        private int IdDistritoField;

        private Slin.Facturacion.Proxies.ServicioConfiguracion.Provincia ProvinciaField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoUbigeo
        {
            get
            {
                return this.CodigoUbigeoField;
            }
            set
            {
                this.CodigoUbigeoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdDistrito
        {
            get
            {
                return this.IdDistritoField;
            }
            set
            {
                this.IdDistritoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Slin.Facturacion.Proxies.ServicioConfiguracion.Provincia Provincia
        {
            get
            {
                return this.ProvinciaField;
            }
            set
            {
                this.ProvinciaField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Provincia", Namespace = "http://schemas.datacontract.org/2004/07/Slin.Facturacion.BusinessEntities")]
    public partial class Provincia : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string CodigoField;

        private Slin.Facturacion.Proxies.ServicioConfiguracion.Departamento DepartamentoField;

        private string DescripcionField;

        private Slin.Facturacion.Proxies.ServicioConfiguracion.Distrito DistritoField;

        private int IdProvinciaField;

        private Slin.Facturacion.Proxies.ServicioConfiguracion.ListaDistrito ListaDistritoField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Slin.Facturacion.Proxies.ServicioConfiguracion.Departamento Departamento
        {
            get
            {
                return this.DepartamentoField;
            }
            set
            {
                this.DepartamentoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Slin.Facturacion.Proxies.ServicioConfiguracion.Distrito Distrito
        {
            get
            {
                return this.DistritoField;
            }
            set
            {
                this.DistritoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProvincia
        {
            get
            {
                return this.IdProvinciaField;
            }
            set
            {
                this.IdProvinciaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Slin.Facturacion.Proxies.ServicioConfiguracion.ListaDistrito ListaDistrito
        {
            get
            {
                return this.ListaDistritoField;
            }
            set
            {
                this.ListaDistritoField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Departamento", Namespace = "http://schemas.datacontract.org/2004/07/Slin.Facturacion.BusinessEntities")]
    public partial class Departamento : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string CodigoField;

        private string DescripcionField;

        private int IdDepartamentoField;

        private Slin.Facturacion.Proxies.ServicioConfiguracion.ListaProvincia ListaProvinciaField;

        private Slin.Facturacion.Proxies.ServicioConfiguracion.Pais PaisField;

        private Slin.Facturacion.Proxies.ServicioConfiguracion.Provincia ProvinciaField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdDepartamento
        {
            get
            {
                return this.IdDepartamentoField;
            }
            set
            {
                this.IdDepartamentoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Slin.Facturacion.Proxies.ServicioConfiguracion.ListaProvincia ListaProvincia
        {
            get
            {
                return this.ListaProvinciaField;
            }
            set
            {
                this.ListaProvinciaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Slin.Facturacion.Proxies.ServicioConfiguracion.Pais Pais
        {
            get
            {
                return this.PaisField;
            }
            set
            {
                this.PaisField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Slin.Facturacion.Proxies.ServicioConfiguracion.Provincia Provincia
        {
            get
            {
                return this.ProvinciaField;
            }
            set
            {
                this.ProvinciaField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name = "ListaDistrito", Namespace = "http://schemas.datacontract.org/2004/07/Slin.Facturacion.BusinessEntities", ItemName = "Distrito")]
    public class ListaDistrito : System.Collections.Generic.List<Slin.Facturacion.Proxies.ServicioConfiguracion.Distrito>
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Pais", Namespace = "http://schemas.datacontract.org/2004/07/Slin.Facturacion.BusinessEntities")]
    public partial class Pais : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string CodigoField;

        private string DescripcionField;

        private int IdPaisField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPais
        {
            get
            {
                return this.IdPaisField;
            }
            set
            {
                this.IdPaisField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name = "ListaProvincia", Namespace = "http://schemas.datacontract.org/2004/07/Slin.Facturacion.BusinessEntities", ItemName = "Provincia")]
    public class ListaProvincia : System.Collections.Generic.List<Slin.Facturacion.Proxies.ServicioConfiguracion.Provincia>
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "TipoCambio", Namespace = "http://schemas.datacontract.org/2004/07/Slin.Facturacion.BusinessEntities.Configu" +
        "racion")]
    public partial class TipoCambio : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string DateValueField;

        private Slin.Facturacion.Proxies.ServicioConfiguracion.Empresa EmpresaField;

        private int IdTipoCambioField;

        private Slin.Facturacion.Proxies.ServicioConfiguracion.Moneda MonedaField;

        private decimal PurchaseValueField;

        private decimal SaleValueField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DateValue
        {
            get
            {
                return this.DateValueField;
            }
            set
            {
                this.DateValueField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Slin.Facturacion.Proxies.ServicioConfiguracion.Empresa Empresa
        {
            get
            {
                return this.EmpresaField;
            }
            set
            {
                this.EmpresaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTipoCambio
        {
            get
            {
                return this.IdTipoCambioField;
            }
            set
            {
                this.IdTipoCambioField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Slin.Facturacion.Proxies.ServicioConfiguracion.Moneda Moneda
        {
            get
            {
                return this.MonedaField;
            }
            set
            {
                this.MonedaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PurchaseValue
        {
            get
            {
                return this.PurchaseValueField;
            }
            set
            {
                this.PurchaseValueField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SaleValue
        {
            get
            {
                return this.SaleValueField;
            }
            set
            {
                this.SaleValueField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Moneda", Namespace = "http://schemas.datacontract.org/2004/07/Slin.Facturacion.BusinessEntities")]
    public partial class Moneda : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string DescripcionField;

        private int IdMonedaField;

        private string SimboloField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdMoneda
        {
            get
            {
                return this.IdMonedaField;
            }
            set
            {
                this.IdMonedaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Simbolo
        {
            get
            {
                return this.SimboloField;
            }
            set
            {
                this.SimboloField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name = "ListaMoneda", Namespace = "http://schemas.datacontract.org/2004/07/Slin.Facturacion.BusinessEntities", ItemName = "Moneda")]
    public class ListaMoneda : System.Collections.Generic.List<Slin.Facturacion.Proxies.ServicioConfiguracion.Moneda>
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name = "ListService", Namespace = "http://schemas.datacontract.org/2004/07/Slin.Facturacion.BusinessEntities.Configu" +
        "racion", ItemName = "Services")]
    public class ListService : System.Collections.Generic.List<Slin.Facturacion.Proxies.ServicioConfiguracion.Services>
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Services", Namespace = "http://schemas.datacontract.org/2004/07/Slin.Facturacion.BusinessEntities.Configu" +
        "racion")]
    public partial class Services : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string CodeServiceField;

        private Slin.Facturacion.Proxies.ServicioConfiguracion.Empresa EmpresaField;

        private Slin.Facturacion.Proxies.ServicioConfiguracion.Estado EstadoField;

        private int IdServiceField;

        private string IntervaleValueField;

        private int MaxNumAttemptsField;

        private string NombreServiceField;

        private string ServiceStatusField;

        private string ValueTimeField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodeService
        {
            get
            {
                return this.CodeServiceField;
            }
            set
            {
                this.CodeServiceField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Slin.Facturacion.Proxies.ServicioConfiguracion.Empresa Empresa
        {
            get
            {
                return this.EmpresaField;
            }
            set
            {
                this.EmpresaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Slin.Facturacion.Proxies.ServicioConfiguracion.Estado Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdService
        {
            get
            {
                return this.IdServiceField;
            }
            set
            {
                this.IdServiceField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IntervaleValue
        {
            get
            {
                return this.IntervaleValueField;
            }
            set
            {
                this.IntervaleValueField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxNumAttempts
        {
            get
            {
                return this.MaxNumAttemptsField;
            }
            set
            {
                this.MaxNumAttemptsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreService
        {
            get
            {
                return this.NombreServiceField;
            }
            set
            {
                this.NombreServiceField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceStatus
        {
            get
            {
                return this.ServiceStatusField;
            }
            set
            {
                this.ServiceStatusField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ValueTime
        {
            get
            {
                return this.ValueTimeField;
            }
            set
            {
                this.ValueTimeField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "TipoDocumento", Namespace = "http://schemas.datacontract.org/2004/07/Slin.Facturacion.BusinessEntities")]
    public partial class TipoDocumento : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string CodigoDocumentoField;

        private string DescripcionField;

        private Slin.Facturacion.Proxies.ServicioConfiguracion.Empresa EmpresaField;

        private Slin.Facturacion.Proxies.ServicioConfiguracion.Estado EstadoField;

        private int IdTipoDocumentoField;

        private int NivelField;

        private int PadreField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoDocumento
        {
            get
            {
                return this.CodigoDocumentoField;
            }
            set
            {
                this.CodigoDocumentoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Slin.Facturacion.Proxies.ServicioConfiguracion.Empresa Empresa
        {
            get
            {
                return this.EmpresaField;
            }
            set
            {
                this.EmpresaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Slin.Facturacion.Proxies.ServicioConfiguracion.Estado Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTipoDocumento
        {
            get
            {
                return this.IdTipoDocumentoField;
            }
            set
            {
                this.IdTipoDocumentoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Nivel
        {
            get
            {
                return this.NivelField;
            }
            set
            {
                this.NivelField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Padre
        {
            get
            {
                return this.PadreField;
            }
            set
            {
                this.PadreField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name = "ListaTipoDocumento", Namespace = "http://schemas.datacontract.org/2004/07/Slin.Facturacion.BusinessEntities", ItemName = "TipoDocumento")]
    public class ListaTipoDocumento : System.Collections.Generic.List<Slin.Facturacion.Proxies.ServicioConfiguracion.TipoDocumento>
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name = "ListSecondaryUser", Namespace = "http://schemas.datacontract.org/2004/07/Slin.Facturacion.BusinessEntities", ItemName = "SecondaryUser")]
    public class ListSecondaryUser : System.Collections.Generic.List<Slin.Facturacion.Proxies.ServicioConfiguracion.SecondaryUser>
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "SecondaryUser", Namespace = "http://schemas.datacontract.org/2004/07/Slin.Facturacion.BusinessEntities")]
    public partial class SecondaryUser : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int IdAmbField;

        private string PasswordField;

        private string RucEntityField;

        private string UserNameField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAmb
        {
            get
            {
                return this.IdAmbField;
            }
            set
            {
                this.IdAmbField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RucEntity
        {
            get
            {
                return this.RucEntityField;
            }
            set
            {
                this.RucEntityField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name = "ListCertificateDigital", Namespace = "http://schemas.datacontract.org/2004/07/Slin.Facturacion.BusinessEntities.Configu" +
        "racion", ItemName = "CertificateDigital")]
    public class ListCertificateDigital : System.Collections.Generic.List<Slin.Facturacion.Proxies.ServicioConfiguracion.CertificateDigital>
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "CertificateDigital", Namespace = "http://schemas.datacontract.org/2004/07/Slin.Facturacion.BusinessEntities.Configu" +
        "racion")]
    public partial class CertificateDigital : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string ExpirationDateField;

        private int IdField;

        private string NameCertificateField;

        private string PwdField;

        private string RucEntityField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExpirationDate
        {
            get
            {
                return this.ExpirationDateField;
            }
            set
            {
                this.ExpirationDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameCertificate
        {
            get
            {
                return this.NameCertificateField;
            }
            set
            {
                this.NameCertificateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pwd
        {
            get
            {
                return this.PwdField;
            }
            set
            {
                this.PwdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RucEntity
        {
            get
            {
                return this.RucEntityField;
            }
            set
            {
                this.RucEntityField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "Slin.Facturacion.Proxies.ServicioConfiguracion.IServicioConfiguracion")]
    public interface IServicioConfiguracion
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioConfiguracion/GetListURLAmbienteSunat", ReplyAction = "http://tempuri.org/IServicioConfiguracion/GetListURLAmbienteSunatResponse")]
        Slin.Facturacion.Proxies.ServicioConfiguracion.ListaURLAmbiente GetListURLAmbienteSunat();

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioConfiguracion/GetListURLAmbienteSunat", ReplyAction = "http://tempuri.org/IServicioConfiguracion/GetListURLAmbienteSunatResponse")]
        System.Threading.Tasks.Task<Slin.Facturacion.Proxies.ServicioConfiguracion.ListaURLAmbiente> GetListURLAmbienteSunatAsync();

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioConfiguracion/GetListaDocAmbiente", ReplyAction = "http://tempuri.org/IServicioConfiguracion/GetListaDocAmbienteResponse")]
        Slin.Facturacion.Proxies.ServicioConfiguracion.ListaDocumentoAmbiente GetListaDocAmbiente(int ID, string RucEntity);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioConfiguracion/GetListaDocAmbiente", ReplyAction = "http://tempuri.org/IServicioConfiguracion/GetListaDocAmbienteResponse")]
        System.Threading.Tasks.Task<Slin.Facturacion.Proxies.ServicioConfiguracion.ListaDocumentoAmbiente> GetListaDocAmbienteAsync(int ID, string RucEntity);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioConfiguracion/InsertDocumentAmbiente", ReplyAction = "http://tempuri.org/IServicioConfiguracion/InsertDocumentAmbienteResponse")]
        string InsertDocumentAmbiente(Slin.Facturacion.Proxies.ServicioConfiguracion.ListaDocumentoAmbiente objListDocAmb);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioConfiguracion/InsertDocumentAmbiente", ReplyAction = "http://tempuri.org/IServicioConfiguracion/InsertDocumentAmbienteResponse")]
        System.Threading.Tasks.Task<string> InsertDocumentAmbienteAsync(Slin.Facturacion.Proxies.ServicioConfiguracion.ListaDocumentoAmbiente objListDocAmb);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioConfiguracion/UpdateDocAmbienteEstado", ReplyAction = "http://tempuri.org/IServicioConfiguracion/UpdateDocAmbienteEstadoResponse")]
        string UpdateDocAmbienteEstado(Slin.Facturacion.Proxies.ServicioConfiguracion.ListaDocumentoAmbiente objListDocAmb);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioConfiguracion/UpdateDocAmbienteEstado", ReplyAction = "http://tempuri.org/IServicioConfiguracion/UpdateDocAmbienteEstadoResponse")]
        System.Threading.Tasks.Task<string> UpdateDocAmbienteEstadoAsync(Slin.Facturacion.Proxies.ServicioConfiguracion.ListaDocumentoAmbiente objListDocAmb);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioConfiguracion/UpdateURLAmbiente", ReplyAction = "http://tempuri.org/IServicioConfiguracion/UpdateURLAmbienteResponse")]
        string UpdateURLAmbiente(Slin.Facturacion.Proxies.ServicioConfiguracion.ListaURLAmbiente objListUrlAmb);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioConfiguracion/UpdateURLAmbiente", ReplyAction = "http://tempuri.org/IServicioConfiguracion/UpdateURLAmbienteResponse")]
        System.Threading.Tasks.Task<string> UpdateURLAmbienteAsync(Slin.Facturacion.Proxies.ServicioConfiguracion.ListaURLAmbiente objListUrlAmb);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioConfiguracion/GetexchangeRateToday", ReplyAction = "http://tempuri.org/IServicioConfiguracion/GetexchangeRateTodayResponse")]
        Slin.Facturacion.Proxies.ServicioConfiguracion.TipoCambio GetexchangeRateToday(string Today, string RucEntity);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioConfiguracion/GetexchangeRateToday", ReplyAction = "http://tempuri.org/IServicioConfiguracion/GetexchangeRateTodayResponse")]
        System.Threading.Tasks.Task<Slin.Facturacion.Proxies.ServicioConfiguracion.TipoCambio> GetexchangeRateTodayAsync(string Today, string RucEntity);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioConfiguracion/GetListMoneda", ReplyAction = "http://tempuri.org/IServicioConfiguracion/GetListMonedaResponse")]
        Slin.Facturacion.Proxies.ServicioConfiguracion.ListaMoneda GetListMoneda();

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioConfiguracion/GetListMoneda", ReplyAction = "http://tempuri.org/IServicioConfiguracion/GetListMonedaResponse")]
        System.Threading.Tasks.Task<Slin.Facturacion.Proxies.ServicioConfiguracion.ListaMoneda> GetListMonedaAsync();

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioConfiguracion/GetListTimeService", ReplyAction = "http://tempuri.org/IServicioConfiguracion/GetListTimeServiceResponse")]
        Slin.Facturacion.Proxies.ServicioConfiguracion.ListService GetListTimeService(string RucEntity);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioConfiguracion/GetListTimeService", ReplyAction = "http://tempuri.org/IServicioConfiguracion/GetListTimeServiceResponse")]
        System.Threading.Tasks.Task<Slin.Facturacion.Proxies.ServicioConfiguracion.ListService> GetListTimeServiceAsync(string RucEntity);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioConfiguracion/UpdateTimeService", ReplyAction = "http://tempuri.org/IServicioConfiguracion/UpdateTimeServiceResponse")]
        string UpdateTimeService(Slin.Facturacion.Proxies.ServicioConfiguracion.Services oService);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioConfiguracion/UpdateTimeService", ReplyAction = "http://tempuri.org/IServicioConfiguracion/UpdateTimeServiceResponse")]
        System.Threading.Tasks.Task<string> UpdateTimeServiceAsync(Slin.Facturacion.Proxies.ServicioConfiguracion.Services oService);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioConfiguracion/InsertExchangeRateToday", ReplyAction = "http://tempuri.org/IServicioConfiguracion/InsertExchangeRateTodayResponse")]
        string InsertExchangeRateToday(Slin.Facturacion.Proxies.ServicioConfiguracion.TipoCambio objRate);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioConfiguracion/InsertExchangeRateToday", ReplyAction = "http://tempuri.org/IServicioConfiguracion/InsertExchangeRateTodayResponse")]
        System.Threading.Tasks.Task<string> InsertExchangeRateTodayAsync(Slin.Facturacion.Proxies.ServicioConfiguracion.TipoCambio objRate);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioConfiguracion/UpdateExchangeRateToday", ReplyAction = "http://tempuri.org/IServicioConfiguracion/UpdateExchangeRateTodayResponse")]
        string UpdateExchangeRateToday(Slin.Facturacion.Proxies.ServicioConfiguracion.TipoCambio objRate);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioConfiguracion/UpdateExchangeRateToday", ReplyAction = "http://tempuri.org/IServicioConfiguracion/UpdateExchangeRateTodayResponse")]
        System.Threading.Tasks.Task<string> UpdateExchangeRateTodayAsync(Slin.Facturacion.Proxies.ServicioConfiguracion.TipoCambio objRate);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioConfiguracion/InsertTypeDocument_ForSend", ReplyAction = "http://tempuri.org/IServicioConfiguracion/InsertTypeDocument_ForSendResponse")]
        string InsertTypeDocument_ForSend(Slin.Facturacion.Proxies.ServicioConfiguracion.TipoDocumento otypedoc);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioConfiguracion/InsertTypeDocument_ForSend", ReplyAction = "http://tempuri.org/IServicioConfiguracion/InsertTypeDocument_ForSendResponse")]
        System.Threading.Tasks.Task<string> InsertTypeDocument_ForSendAsync(Slin.Facturacion.Proxies.ServicioConfiguracion.TipoDocumento otypedoc);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioConfiguracion/InsertTypeDocument_ForPrint", ReplyAction = "http://tempuri.org/IServicioConfiguracion/InsertTypeDocument_ForPrintResponse")]
        string InsertTypeDocument_ForPrint(Slin.Facturacion.Proxies.ServicioConfiguracion.TipoDocumento otypedoc);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioConfiguracion/InsertTypeDocument_ForPrint", ReplyAction = "http://tempuri.org/IServicioConfiguracion/InsertTypeDocument_ForPrintResponse")]
        System.Threading.Tasks.Task<string> InsertTypeDocument_ForPrintAsync(Slin.Facturacion.Proxies.ServicioConfiguracion.TipoDocumento otypedoc);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioConfiguracion/ListTypeDocument_TypeSend", ReplyAction = "http://tempuri.org/IServicioConfiguracion/ListTypeDocument_TypeSendResponse")]
        Slin.Facturacion.Proxies.ServicioConfiguracion.ListaTipoDocumento ListTypeDocument_TypeSend(string RucEntity);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioConfiguracion/ListTypeDocument_TypeSend", ReplyAction = "http://tempuri.org/IServicioConfiguracion/ListTypeDocument_TypeSendResponse")]
        System.Threading.Tasks.Task<Slin.Facturacion.Proxies.ServicioConfiguracion.ListaTipoDocumento> ListTypeDocument_TypeSendAsync(string RucEntity);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioConfiguracion/ListTypeDocument_TypePrint", ReplyAction = "http://tempuri.org/IServicioConfiguracion/ListTypeDocument_TypePrintResponse")]
        Slin.Facturacion.Proxies.ServicioConfiguracion.ListaTipoDocumento ListTypeDocument_TypePrint(string RucEntity);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioConfiguracion/ListTypeDocument_TypePrint", ReplyAction = "http://tempuri.org/IServicioConfiguracion/ListTypeDocument_TypePrintResponse")]
        System.Threading.Tasks.Task<Slin.Facturacion.Proxies.ServicioConfiguracion.ListaTipoDocumento> ListTypeDocument_TypePrintAsync(string RucEntity);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioConfiguracion/Get_SecondaryUserSunat", ReplyAction = "http://tempuri.org/IServicioConfiguracion/Get_SecondaryUserSunatResponse")]
        Slin.Facturacion.Proxies.ServicioConfiguracion.ListSecondaryUser Get_SecondaryUserSunat(int IdAmb, string RucEntity);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioConfiguracion/Get_SecondaryUserSunat", ReplyAction = "http://tempuri.org/IServicioConfiguracion/Get_SecondaryUserSunatResponse")]
        System.Threading.Tasks.Task<Slin.Facturacion.Proxies.ServicioConfiguracion.ListSecondaryUser> Get_SecondaryUserSunatAsync(int IdAmb, string RucEntity);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioConfiguracion/Insert_SecondaryUserSunat_Amb", ReplyAction = "http://tempuri.org/IServicioConfiguracion/Insert_SecondaryUserSunat_AmbResponse")]
        string Insert_SecondaryUserSunat_Amb(Slin.Facturacion.Proxies.ServicioConfiguracion.SecondaryUser objSeconUser);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioConfiguracion/Insert_SecondaryUserSunat_Amb", ReplyAction = "http://tempuri.org/IServicioConfiguracion/Insert_SecondaryUserSunat_AmbResponse")]
        System.Threading.Tasks.Task<string> Insert_SecondaryUserSunat_AmbAsync(Slin.Facturacion.Proxies.ServicioConfiguracion.SecondaryUser objSeconUser);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioConfiguracion/Get_CertificateDigitalInformation", ReplyAction = "http://tempuri.org/IServicioConfiguracion/Get_CertificateDigitalInformationRespon" +
            "se")]
        Slin.Facturacion.Proxies.ServicioConfiguracion.ListCertificateDigital Get_CertificateDigitalInformation(string RucEntity);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioConfiguracion/Get_CertificateDigitalInformation", ReplyAction = "http://tempuri.org/IServicioConfiguracion/Get_CertificateDigitalInformationRespon" +
            "se")]
        System.Threading.Tasks.Task<Slin.Facturacion.Proxies.ServicioConfiguracion.ListCertificateDigital> Get_CertificateDigitalInformationAsync(string RucEntity);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioConfiguracionChannel : Slin.Facturacion.Proxies.ServicioConfiguracion.IServicioConfiguracion, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioConfiguracionClient : System.ServiceModel.ClientBase<Slin.Facturacion.Proxies.ServicioConfiguracion.IServicioConfiguracion>, Slin.Facturacion.Proxies.ServicioConfiguracion.IServicioConfiguracion
    {

        public ServicioConfiguracionClient()
        {
        }

        public ServicioConfiguracionClient(string endpointConfigurationName) :
                base(endpointConfigurationName)
        {
        }

        public ServicioConfiguracionClient(string endpointConfigurationName, string remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public ServicioConfiguracionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public ServicioConfiguracionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        public Slin.Facturacion.Proxies.ServicioConfiguracion.ListaURLAmbiente GetListURLAmbienteSunat()
        {
            return base.Channel.GetListURLAmbienteSunat();
        }

        public System.Threading.Tasks.Task<Slin.Facturacion.Proxies.ServicioConfiguracion.ListaURLAmbiente> GetListURLAmbienteSunatAsync()
        {
            return base.Channel.GetListURLAmbienteSunatAsync();
        }

        public Slin.Facturacion.Proxies.ServicioConfiguracion.ListaDocumentoAmbiente GetListaDocAmbiente(int ID, string RucEntity)
        {
            return base.Channel.GetListaDocAmbiente(ID, RucEntity);
        }

        public System.Threading.Tasks.Task<Slin.Facturacion.Proxies.ServicioConfiguracion.ListaDocumentoAmbiente> GetListaDocAmbienteAsync(int ID, string RucEntity)
        {
            return base.Channel.GetListaDocAmbienteAsync(ID, RucEntity);
        }

        public string InsertDocumentAmbiente(Slin.Facturacion.Proxies.ServicioConfiguracion.ListaDocumentoAmbiente objListDocAmb)
        {
            return base.Channel.InsertDocumentAmbiente(objListDocAmb);
        }

        public System.Threading.Tasks.Task<string> InsertDocumentAmbienteAsync(Slin.Facturacion.Proxies.ServicioConfiguracion.ListaDocumentoAmbiente objListDocAmb)
        {
            return base.Channel.InsertDocumentAmbienteAsync(objListDocAmb);
        }

        public string UpdateDocAmbienteEstado(Slin.Facturacion.Proxies.ServicioConfiguracion.ListaDocumentoAmbiente objListDocAmb)
        {
            return base.Channel.UpdateDocAmbienteEstado(objListDocAmb);
        }

        public System.Threading.Tasks.Task<string> UpdateDocAmbienteEstadoAsync(Slin.Facturacion.Proxies.ServicioConfiguracion.ListaDocumentoAmbiente objListDocAmb)
        {
            return base.Channel.UpdateDocAmbienteEstadoAsync(objListDocAmb);
        }

        public string UpdateURLAmbiente(Slin.Facturacion.Proxies.ServicioConfiguracion.ListaURLAmbiente objListUrlAmb)
        {
            return base.Channel.UpdateURLAmbiente(objListUrlAmb);
        }

        public System.Threading.Tasks.Task<string> UpdateURLAmbienteAsync(Slin.Facturacion.Proxies.ServicioConfiguracion.ListaURLAmbiente objListUrlAmb)
        {
            return base.Channel.UpdateURLAmbienteAsync(objListUrlAmb);
        }

        public Slin.Facturacion.Proxies.ServicioConfiguracion.TipoCambio GetexchangeRateToday(string Today, string RucEntity)
        {
            return base.Channel.GetexchangeRateToday(Today, RucEntity);
        }

        public System.Threading.Tasks.Task<Slin.Facturacion.Proxies.ServicioConfiguracion.TipoCambio> GetexchangeRateTodayAsync(string Today, string RucEntity)
        {
            return base.Channel.GetexchangeRateTodayAsync(Today, RucEntity);
        }

        public Slin.Facturacion.Proxies.ServicioConfiguracion.ListaMoneda GetListMoneda()
        {
            return base.Channel.GetListMoneda();
        }

        public System.Threading.Tasks.Task<Slin.Facturacion.Proxies.ServicioConfiguracion.ListaMoneda> GetListMonedaAsync()
        {
            return base.Channel.GetListMonedaAsync();
        }

        public Slin.Facturacion.Proxies.ServicioConfiguracion.ListService GetListTimeService(string RucEntity)
        {
            return base.Channel.GetListTimeService(RucEntity);
        }

        public System.Threading.Tasks.Task<Slin.Facturacion.Proxies.ServicioConfiguracion.ListService> GetListTimeServiceAsync(string RucEntity)
        {
            return base.Channel.GetListTimeServiceAsync(RucEntity);
        }

        public string UpdateTimeService(Slin.Facturacion.Proxies.ServicioConfiguracion.Services oService)
        {
            return base.Channel.UpdateTimeService(oService);
        }

        public System.Threading.Tasks.Task<string> UpdateTimeServiceAsync(Slin.Facturacion.Proxies.ServicioConfiguracion.Services oService)
        {
            return base.Channel.UpdateTimeServiceAsync(oService);
        }

        public string InsertExchangeRateToday(Slin.Facturacion.Proxies.ServicioConfiguracion.TipoCambio objRate)
        {
            return base.Channel.InsertExchangeRateToday(objRate);
        }

        public System.Threading.Tasks.Task<string> InsertExchangeRateTodayAsync(Slin.Facturacion.Proxies.ServicioConfiguracion.TipoCambio objRate)
        {
            return base.Channel.InsertExchangeRateTodayAsync(objRate);
        }

        public string UpdateExchangeRateToday(Slin.Facturacion.Proxies.ServicioConfiguracion.TipoCambio objRate)
        {
            return base.Channel.UpdateExchangeRateToday(objRate);
        }

        public System.Threading.Tasks.Task<string> UpdateExchangeRateTodayAsync(Slin.Facturacion.Proxies.ServicioConfiguracion.TipoCambio objRate)
        {
            return base.Channel.UpdateExchangeRateTodayAsync(objRate);
        }

        public string InsertTypeDocument_ForSend(Slin.Facturacion.Proxies.ServicioConfiguracion.TipoDocumento otypedoc)
        {
            return base.Channel.InsertTypeDocument_ForSend(otypedoc);
        }

        public System.Threading.Tasks.Task<string> InsertTypeDocument_ForSendAsync(Slin.Facturacion.Proxies.ServicioConfiguracion.TipoDocumento otypedoc)
        {
            return base.Channel.InsertTypeDocument_ForSendAsync(otypedoc);
        }

        public string InsertTypeDocument_ForPrint(Slin.Facturacion.Proxies.ServicioConfiguracion.TipoDocumento otypedoc)
        {
            return base.Channel.InsertTypeDocument_ForPrint(otypedoc);
        }

        public System.Threading.Tasks.Task<string> InsertTypeDocument_ForPrintAsync(Slin.Facturacion.Proxies.ServicioConfiguracion.TipoDocumento otypedoc)
        {
            return base.Channel.InsertTypeDocument_ForPrintAsync(otypedoc);
        }

        public Slin.Facturacion.Proxies.ServicioConfiguracion.ListaTipoDocumento ListTypeDocument_TypeSend(string RucEntity)
        {
            return base.Channel.ListTypeDocument_TypeSend(RucEntity);
        }

        public System.Threading.Tasks.Task<Slin.Facturacion.Proxies.ServicioConfiguracion.ListaTipoDocumento> ListTypeDocument_TypeSendAsync(string RucEntity)
        {
            return base.Channel.ListTypeDocument_TypeSendAsync(RucEntity);
        }

        public Slin.Facturacion.Proxies.ServicioConfiguracion.ListaTipoDocumento ListTypeDocument_TypePrint(string RucEntity)
        {
            return base.Channel.ListTypeDocument_TypePrint(RucEntity);
        }

        public System.Threading.Tasks.Task<Slin.Facturacion.Proxies.ServicioConfiguracion.ListaTipoDocumento> ListTypeDocument_TypePrintAsync(string RucEntity)
        {
            return base.Channel.ListTypeDocument_TypePrintAsync(RucEntity);
        }

        public Slin.Facturacion.Proxies.ServicioConfiguracion.ListSecondaryUser Get_SecondaryUserSunat(int IdAmb, string RucEntity)
        {
            return base.Channel.Get_SecondaryUserSunat(IdAmb, RucEntity);
        }

        public System.Threading.Tasks.Task<Slin.Facturacion.Proxies.ServicioConfiguracion.ListSecondaryUser> Get_SecondaryUserSunatAsync(int IdAmb, string RucEntity)
        {
            return base.Channel.Get_SecondaryUserSunatAsync(IdAmb, RucEntity);
        }

        public string Insert_SecondaryUserSunat_Amb(Slin.Facturacion.Proxies.ServicioConfiguracion.SecondaryUser objSeconUser)
        {
            return base.Channel.Insert_SecondaryUserSunat_Amb(objSeconUser);
        }

        public System.Threading.Tasks.Task<string> Insert_SecondaryUserSunat_AmbAsync(Slin.Facturacion.Proxies.ServicioConfiguracion.SecondaryUser objSeconUser)
        {
            return base.Channel.Insert_SecondaryUserSunat_AmbAsync(objSeconUser);
        }

        public Slin.Facturacion.Proxies.ServicioConfiguracion.ListCertificateDigital Get_CertificateDigitalInformation(string RucEntity)
        {
            return base.Channel.Get_CertificateDigitalInformation(RucEntity);
        }

        public System.Threading.Tasks.Task<Slin.Facturacion.Proxies.ServicioConfiguracion.ListCertificateDigital> Get_CertificateDigitalInformationAsync(string RucEntity)
        {
            return base.Channel.Get_CertificateDigitalInformationAsync(RucEntity);
        }
    }
}
