//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Slin.Facturacion.Proxies.ServicioResumen
{


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "Slin.Facturacion.Proxies.ServicioResumen.IServicioResumen")]
    public interface IServicioResumen
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioResumen/ProcesaResumen", ReplyAction = "http://tempuri.org/IServicioResumen/ProcesaResumenResponse")]
        string ProcesaResumen(string fecha, string ruc, string tipo);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServicioResumen/ProcesaResumen", ReplyAction = "http://tempuri.org/IServicioResumen/ProcesaResumenResponse")]
        System.Threading.Tasks.Task<string> ProcesaResumenAsync(string fecha, string ruc, string tipo);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioResumenChannel : Slin.Facturacion.Proxies.ServicioResumen.IServicioResumen, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioResumenClient : System.ServiceModel.ClientBase<Slin.Facturacion.Proxies.ServicioResumen.IServicioResumen>, Slin.Facturacion.Proxies.ServicioResumen.IServicioResumen
    {

        public ServicioResumenClient()
        {
        }

        public ServicioResumenClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
        {
        }

        public ServicioResumenClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public ServicioResumenClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public ServicioResumenClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        public string ProcesaResumen(string fecha, string ruc, string tipo)
        {
            return base.Channel.ProcesaResumen(fecha, ruc, tipo);
        }

        public System.Threading.Tasks.Task<string> ProcesaResumenAsync(string fecha, string ruc, string tipo)
        {
            return base.Channel.ProcesaResumenAsync(fecha, ruc, tipo);
        }
    }
}
