//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebService.ServiceReferenceXml {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.slin.com.pe/", ConfigurationName="ServiceReferenceXml.ServicioInterfaceXmlSoap")]
    public interface ServicioInterfaceXmlSoap {
        
        // CODEGEN: Generating message contract since element name xmlLine from namespace http://www.slin.com.pe/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.slin.com.pe/GetObjInterfaceXML", ReplyAction="*")]
        TestWebService.ServiceReferenceXml.GetObjInterfaceXMLResponse GetObjInterfaceXML(TestWebService.ServiceReferenceXml.GetObjInterfaceXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.slin.com.pe/GetObjInterfaceXML", ReplyAction="*")]
        System.Threading.Tasks.Task<TestWebService.ServiceReferenceXml.GetObjInterfaceXMLResponse> GetObjInterfaceXMLAsync(TestWebService.ServiceReferenceXml.GetObjInterfaceXMLRequest request);
        
        // CODEGEN: Generating message contract since element name xmlLine from namespace http://www.slin.com.pe/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.slin.com.pe/GetObjInterfaceXML_CE", ReplyAction="*")]
        TestWebService.ServiceReferenceXml.GetObjInterfaceXML_CEResponse GetObjInterfaceXML_CE(TestWebService.ServiceReferenceXml.GetObjInterfaceXML_CERequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.slin.com.pe/GetObjInterfaceXML_CE", ReplyAction="*")]
        System.Threading.Tasks.Task<TestWebService.ServiceReferenceXml.GetObjInterfaceXML_CEResponse> GetObjInterfaceXML_CEAsync(TestWebService.ServiceReferenceXml.GetObjInterfaceXML_CERequest request);
        
        // CODEGEN: Generating message contract since element name xmlLine from namespace http://www.slin.com.pe/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.slin.com.pe/GetObjInterfaceXML_CENOTE", ReplyAction="*")]
        TestWebService.ServiceReferenceXml.GetObjInterfaceXML_CENOTEResponse GetObjInterfaceXML_CENOTE(TestWebService.ServiceReferenceXml.GetObjInterfaceXML_CENOTERequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.slin.com.pe/GetObjInterfaceXML_CENOTE", ReplyAction="*")]
        System.Threading.Tasks.Task<TestWebService.ServiceReferenceXml.GetObjInterfaceXML_CENOTEResponse> GetObjInterfaceXML_CENOTEAsync(TestWebService.ServiceReferenceXml.GetObjInterfaceXML_CENOTERequest request);
        
        // CODEGEN: Generating message contract since element name xmlLine from namespace http://www.slin.com.pe/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.slin.com.pe/SendDocumentVoided", ReplyAction="*")]
        TestWebService.ServiceReferenceXml.SendDocumentVoidedResponse SendDocumentVoided(TestWebService.ServiceReferenceXml.SendDocumentVoidedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.slin.com.pe/SendDocumentVoided", ReplyAction="*")]
        System.Threading.Tasks.Task<TestWebService.ServiceReferenceXml.SendDocumentVoidedResponse> SendDocumentVoidedAsync(TestWebService.ServiceReferenceXml.SendDocumentVoidedRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetObjInterfaceXMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetObjInterfaceXML", Namespace="http://www.slin.com.pe/", Order=0)]
        public TestWebService.ServiceReferenceXml.GetObjInterfaceXMLRequestBody Body;
        
        public GetObjInterfaceXMLRequest() {
        }
        
        public GetObjInterfaceXMLRequest(TestWebService.ServiceReferenceXml.GetObjInterfaceXMLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.slin.com.pe/")]
    public partial class GetObjInterfaceXMLRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xmlLine;
        
        public GetObjInterfaceXMLRequestBody() {
        }
        
        public GetObjInterfaceXMLRequestBody(string xmlLine) {
            this.xmlLine = xmlLine;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetObjInterfaceXMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetObjInterfaceXMLResponse", Namespace="http://www.slin.com.pe/", Order=0)]
        public TestWebService.ServiceReferenceXml.GetObjInterfaceXMLResponseBody Body;
        
        public GetObjInterfaceXMLResponse() {
        }
        
        public GetObjInterfaceXMLResponse(TestWebService.ServiceReferenceXml.GetObjInterfaceXMLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.slin.com.pe/")]
    public partial class GetObjInterfaceXMLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetObjInterfaceXMLResult;
        
        public GetObjInterfaceXMLResponseBody() {
        }
        
        public GetObjInterfaceXMLResponseBody(string GetObjInterfaceXMLResult) {
            this.GetObjInterfaceXMLResult = GetObjInterfaceXMLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetObjInterfaceXML_CERequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetObjInterfaceXML_CE", Namespace="http://www.slin.com.pe/", Order=0)]
        public TestWebService.ServiceReferenceXml.GetObjInterfaceXML_CERequestBody Body;
        
        public GetObjInterfaceXML_CERequest() {
        }
        
        public GetObjInterfaceXML_CERequest(TestWebService.ServiceReferenceXml.GetObjInterfaceXML_CERequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.slin.com.pe/")]
    public partial class GetObjInterfaceXML_CERequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xmlLine;
        
        public GetObjInterfaceXML_CERequestBody() {
        }
        
        public GetObjInterfaceXML_CERequestBody(string xmlLine) {
            this.xmlLine = xmlLine;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetObjInterfaceXML_CEResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetObjInterfaceXML_CEResponse", Namespace="http://www.slin.com.pe/", Order=0)]
        public TestWebService.ServiceReferenceXml.GetObjInterfaceXML_CEResponseBody Body;
        
        public GetObjInterfaceXML_CEResponse() {
        }
        
        public GetObjInterfaceXML_CEResponse(TestWebService.ServiceReferenceXml.GetObjInterfaceXML_CEResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.slin.com.pe/")]
    public partial class GetObjInterfaceXML_CEResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetObjInterfaceXML_CEResult;
        
        public GetObjInterfaceXML_CEResponseBody() {
        }
        
        public GetObjInterfaceXML_CEResponseBody(string GetObjInterfaceXML_CEResult) {
            this.GetObjInterfaceXML_CEResult = GetObjInterfaceXML_CEResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetObjInterfaceXML_CENOTERequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetObjInterfaceXML_CENOTE", Namespace="http://www.slin.com.pe/", Order=0)]
        public TestWebService.ServiceReferenceXml.GetObjInterfaceXML_CENOTERequestBody Body;
        
        public GetObjInterfaceXML_CENOTERequest() {
        }
        
        public GetObjInterfaceXML_CENOTERequest(TestWebService.ServiceReferenceXml.GetObjInterfaceXML_CENOTERequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.slin.com.pe/")]
    public partial class GetObjInterfaceXML_CENOTERequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xmlLine;
        
        public GetObjInterfaceXML_CENOTERequestBody() {
        }
        
        public GetObjInterfaceXML_CENOTERequestBody(string xmlLine) {
            this.xmlLine = xmlLine;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetObjInterfaceXML_CENOTEResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetObjInterfaceXML_CENOTEResponse", Namespace="http://www.slin.com.pe/", Order=0)]
        public TestWebService.ServiceReferenceXml.GetObjInterfaceXML_CENOTEResponseBody Body;
        
        public GetObjInterfaceXML_CENOTEResponse() {
        }
        
        public GetObjInterfaceXML_CENOTEResponse(TestWebService.ServiceReferenceXml.GetObjInterfaceXML_CENOTEResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.slin.com.pe/")]
    public partial class GetObjInterfaceXML_CENOTEResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetObjInterfaceXML_CENOTEResult;
        
        public GetObjInterfaceXML_CENOTEResponseBody() {
        }
        
        public GetObjInterfaceXML_CENOTEResponseBody(string GetObjInterfaceXML_CENOTEResult) {
            this.GetObjInterfaceXML_CENOTEResult = GetObjInterfaceXML_CENOTEResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendDocumentVoidedRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendDocumentVoided", Namespace="http://www.slin.com.pe/", Order=0)]
        public TestWebService.ServiceReferenceXml.SendDocumentVoidedRequestBody Body;
        
        public SendDocumentVoidedRequest() {
        }
        
        public SendDocumentVoidedRequest(TestWebService.ServiceReferenceXml.SendDocumentVoidedRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.slin.com.pe/")]
    public partial class SendDocumentVoidedRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xmlLine;
        
        public SendDocumentVoidedRequestBody() {
        }
        
        public SendDocumentVoidedRequestBody(string xmlLine) {
            this.xmlLine = xmlLine;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendDocumentVoidedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendDocumentVoidedResponse", Namespace="http://www.slin.com.pe/", Order=0)]
        public TestWebService.ServiceReferenceXml.SendDocumentVoidedResponseBody Body;
        
        public SendDocumentVoidedResponse() {
        }
        
        public SendDocumentVoidedResponse(TestWebService.ServiceReferenceXml.SendDocumentVoidedResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.slin.com.pe/")]
    public partial class SendDocumentVoidedResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendDocumentVoidedResult;
        
        public SendDocumentVoidedResponseBody() {
        }
        
        public SendDocumentVoidedResponseBody(string SendDocumentVoidedResult) {
            this.SendDocumentVoidedResult = SendDocumentVoidedResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioInterfaceXmlSoapChannel : TestWebService.ServiceReferenceXml.ServicioInterfaceXmlSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioInterfaceXmlSoapClient : System.ServiceModel.ClientBase<TestWebService.ServiceReferenceXml.ServicioInterfaceXmlSoap>, TestWebService.ServiceReferenceXml.ServicioInterfaceXmlSoap {
        
        public ServicioInterfaceXmlSoapClient() {
        }
        
        public ServicioInterfaceXmlSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioInterfaceXmlSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioInterfaceXmlSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioInterfaceXmlSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestWebService.ServiceReferenceXml.GetObjInterfaceXMLResponse TestWebService.ServiceReferenceXml.ServicioInterfaceXmlSoap.GetObjInterfaceXML(TestWebService.ServiceReferenceXml.GetObjInterfaceXMLRequest request) {
            return base.Channel.GetObjInterfaceXML(request);
        }
        
        public string GetObjInterfaceXML(string xmlLine) {
            TestWebService.ServiceReferenceXml.GetObjInterfaceXMLRequest inValue = new TestWebService.ServiceReferenceXml.GetObjInterfaceXMLRequest();
            inValue.Body = new TestWebService.ServiceReferenceXml.GetObjInterfaceXMLRequestBody();
            inValue.Body.xmlLine = xmlLine;
            TestWebService.ServiceReferenceXml.GetObjInterfaceXMLResponse retVal = ((TestWebService.ServiceReferenceXml.ServicioInterfaceXmlSoap)(this)).GetObjInterfaceXML(inValue);
            return retVal.Body.GetObjInterfaceXMLResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestWebService.ServiceReferenceXml.GetObjInterfaceXMLResponse> TestWebService.ServiceReferenceXml.ServicioInterfaceXmlSoap.GetObjInterfaceXMLAsync(TestWebService.ServiceReferenceXml.GetObjInterfaceXMLRequest request) {
            return base.Channel.GetObjInterfaceXMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestWebService.ServiceReferenceXml.GetObjInterfaceXMLResponse> GetObjInterfaceXMLAsync(string xmlLine) {
            TestWebService.ServiceReferenceXml.GetObjInterfaceXMLRequest inValue = new TestWebService.ServiceReferenceXml.GetObjInterfaceXMLRequest();
            inValue.Body = new TestWebService.ServiceReferenceXml.GetObjInterfaceXMLRequestBody();
            inValue.Body.xmlLine = xmlLine;
            return ((TestWebService.ServiceReferenceXml.ServicioInterfaceXmlSoap)(this)).GetObjInterfaceXMLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestWebService.ServiceReferenceXml.GetObjInterfaceXML_CEResponse TestWebService.ServiceReferenceXml.ServicioInterfaceXmlSoap.GetObjInterfaceXML_CE(TestWebService.ServiceReferenceXml.GetObjInterfaceXML_CERequest request) {
            return base.Channel.GetObjInterfaceXML_CE(request);
        }
        
        public string GetObjInterfaceXML_CE(string xmlLine) {
            TestWebService.ServiceReferenceXml.GetObjInterfaceXML_CERequest inValue = new TestWebService.ServiceReferenceXml.GetObjInterfaceXML_CERequest();
            inValue.Body = new TestWebService.ServiceReferenceXml.GetObjInterfaceXML_CERequestBody();
            inValue.Body.xmlLine = xmlLine;
            TestWebService.ServiceReferenceXml.GetObjInterfaceXML_CEResponse retVal = ((TestWebService.ServiceReferenceXml.ServicioInterfaceXmlSoap)(this)).GetObjInterfaceXML_CE(inValue);
            return retVal.Body.GetObjInterfaceXML_CEResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestWebService.ServiceReferenceXml.GetObjInterfaceXML_CEResponse> TestWebService.ServiceReferenceXml.ServicioInterfaceXmlSoap.GetObjInterfaceXML_CEAsync(TestWebService.ServiceReferenceXml.GetObjInterfaceXML_CERequest request) {
            return base.Channel.GetObjInterfaceXML_CEAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestWebService.ServiceReferenceXml.GetObjInterfaceXML_CEResponse> GetObjInterfaceXML_CEAsync(string xmlLine) {
            TestWebService.ServiceReferenceXml.GetObjInterfaceXML_CERequest inValue = new TestWebService.ServiceReferenceXml.GetObjInterfaceXML_CERequest();
            inValue.Body = new TestWebService.ServiceReferenceXml.GetObjInterfaceXML_CERequestBody();
            inValue.Body.xmlLine = xmlLine;
            return ((TestWebService.ServiceReferenceXml.ServicioInterfaceXmlSoap)(this)).GetObjInterfaceXML_CEAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestWebService.ServiceReferenceXml.GetObjInterfaceXML_CENOTEResponse TestWebService.ServiceReferenceXml.ServicioInterfaceXmlSoap.GetObjInterfaceXML_CENOTE(TestWebService.ServiceReferenceXml.GetObjInterfaceXML_CENOTERequest request) {
            return base.Channel.GetObjInterfaceXML_CENOTE(request);
        }
        
        public string GetObjInterfaceXML_CENOTE(string xmlLine) {
            TestWebService.ServiceReferenceXml.GetObjInterfaceXML_CENOTERequest inValue = new TestWebService.ServiceReferenceXml.GetObjInterfaceXML_CENOTERequest();
            inValue.Body = new TestWebService.ServiceReferenceXml.GetObjInterfaceXML_CENOTERequestBody();
            inValue.Body.xmlLine = xmlLine;
            TestWebService.ServiceReferenceXml.GetObjInterfaceXML_CENOTEResponse retVal = ((TestWebService.ServiceReferenceXml.ServicioInterfaceXmlSoap)(this)).GetObjInterfaceXML_CENOTE(inValue);
            return retVal.Body.GetObjInterfaceXML_CENOTEResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestWebService.ServiceReferenceXml.GetObjInterfaceXML_CENOTEResponse> TestWebService.ServiceReferenceXml.ServicioInterfaceXmlSoap.GetObjInterfaceXML_CENOTEAsync(TestWebService.ServiceReferenceXml.GetObjInterfaceXML_CENOTERequest request) {
            return base.Channel.GetObjInterfaceXML_CENOTEAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestWebService.ServiceReferenceXml.GetObjInterfaceXML_CENOTEResponse> GetObjInterfaceXML_CENOTEAsync(string xmlLine) {
            TestWebService.ServiceReferenceXml.GetObjInterfaceXML_CENOTERequest inValue = new TestWebService.ServiceReferenceXml.GetObjInterfaceXML_CENOTERequest();
            inValue.Body = new TestWebService.ServiceReferenceXml.GetObjInterfaceXML_CENOTERequestBody();
            inValue.Body.xmlLine = xmlLine;
            return ((TestWebService.ServiceReferenceXml.ServicioInterfaceXmlSoap)(this)).GetObjInterfaceXML_CENOTEAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestWebService.ServiceReferenceXml.SendDocumentVoidedResponse TestWebService.ServiceReferenceXml.ServicioInterfaceXmlSoap.SendDocumentVoided(TestWebService.ServiceReferenceXml.SendDocumentVoidedRequest request) {
            return base.Channel.SendDocumentVoided(request);
        }
        
        public string SendDocumentVoided(string xmlLine) {
            TestWebService.ServiceReferenceXml.SendDocumentVoidedRequest inValue = new TestWebService.ServiceReferenceXml.SendDocumentVoidedRequest();
            inValue.Body = new TestWebService.ServiceReferenceXml.SendDocumentVoidedRequestBody();
            inValue.Body.xmlLine = xmlLine;
            TestWebService.ServiceReferenceXml.SendDocumentVoidedResponse retVal = ((TestWebService.ServiceReferenceXml.ServicioInterfaceXmlSoap)(this)).SendDocumentVoided(inValue);
            return retVal.Body.SendDocumentVoidedResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestWebService.ServiceReferenceXml.SendDocumentVoidedResponse> TestWebService.ServiceReferenceXml.ServicioInterfaceXmlSoap.SendDocumentVoidedAsync(TestWebService.ServiceReferenceXml.SendDocumentVoidedRequest request) {
            return base.Channel.SendDocumentVoidedAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestWebService.ServiceReferenceXml.SendDocumentVoidedResponse> SendDocumentVoidedAsync(string xmlLine) {
            TestWebService.ServiceReferenceXml.SendDocumentVoidedRequest inValue = new TestWebService.ServiceReferenceXml.SendDocumentVoidedRequest();
            inValue.Body = new TestWebService.ServiceReferenceXml.SendDocumentVoidedRequestBody();
            inValue.Body.xmlLine = xmlLine;
            return ((TestWebService.ServiceReferenceXml.ServicioInterfaceXmlSoap)(this)).SendDocumentVoidedAsync(inValue);
        }
    }
}
